Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2018-09, with the labels that each got.

#10 Init component repository
  .babelrc.js
  .browserslistrc
  .editorconfig
  .eslintrc.js
  .gitignore
  .npmignore
  .stylelintrc.js
  Makefile
  dist/ncvuecomponents.js
  dist/ncvuecomponents.js.map
  lerna.json
  package-lock.json
  package.json
  src/components/AppNavigation/AppNavigation.vue
  src/components/AppNavigation/AppNavigationItem.vue
  src/components/AppNavigation/index.js
  src/components/DatetimePicker/index.js
  src/components/DatetimePicker/index.scss
  src/components/PopoverMenu/PopoverMenu.vue
  src/components/PopoverMenu/PopoverMenuItem.vue
  src/components/PopoverMenu/index.js
  src/components/index.js
  src/index.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: 2. developing, enhancement, feature: app-navigation, feature: datepicker, feature: popovermenu

#20 Add installation doc
  README.md
Labels: 3. to review, enhancement, feature: documentation

#19 Add npm badge to readme
  README.md
Labels: 3. to review, enhancement

#23 Datepicker headers, time, date and scroll style fixes
  dist/ncvuecomponents.js
  dist/ncvuecomponents.js.map
  package-lock.json
  src/components/DatetimePicker/index.scss
Labels: 3. to review, design, feature: datepicker, high

#28 bg color correction
  src/components/DatetimePicker/index.scss
Labels: design

#26 Change entry point, fix babel and update
  dist/ncvuecomponents.js
  dist/ncvuecomponents.js.map
  package-lock.json
  package.json
  src/components/PopoverMenu/PopoverMenuItem.vue
  src/index.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: 2. developing, help wanted, high

#33 Make exact routing optional in AppNavigationItem
  dist/ncvuecomponents.js
  dist/ncvuecomponents.js.map
  src/components/AppNavigation/AppNavigationItem.vue
Labels: 3. to review, bug

#40 Add Travis config
  .travis.yml
Labels: 3. to review
