Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2018-10, with the labels that each got.

#67 Fix a webpack devtool that works without unsave-eval CSP
  webpack.dev.js
Labels: 3. to review, bug

#69 Fix travis
  .eslintrc.js
  .travis.yml
  package.json
  src/components/AppNavigation/AppNavigation.vue
  src/components/AppNavigation/AppNavigationItem.vue
  src/components/PopoverMenu/PopoverMenu.vue
  src/components/PopoverMenu/PopoverMenuItem.vue
Labels: configuration, dependencies, high

#68 Copyright typo fix
  LICENSE
  packages/webpack4-template-simple/template/src/App.vue
  packages/webpack4-template-simple/template/src/main.js
  src/components/AppNavigation/AppNavigation.vue
  src/components/AppNavigation/AppNavigationItem.vue
  src/components/AppNavigation/index.js
  src/components/DatetimePicker/index.js
  src/components/Multiselect/index.js
  src/components/PopoverMenu/PopoverMenu.vue
  src/components/PopoverMenu/PopoverMenuItem.vue
  src/components/PopoverMenu/index.js
  src/components/index.js
  src/index.js
Labels: 3. to review

#76 Adding avatar updates after user change and group support
  src/components/Avatar/Avatar.vue
Labels: 3. to review, bug, feature: avatar
