Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2019-10, with the labels that each got.

#621 Use @nextcloud/axios
  package-lock.json
  package.json
  src/components/Avatar/Avatar.vue
Labels: 4. to release

#619 Make "more icon" of actions customizable
  src/components/Actions/Actions.vue
Labels: 3. to review

#622 Allow to close the actions menu after click
  src/components/ActionButton/ActionButton.vue
  src/mixins/actionText.js
Labels: 3. to review, feature: actions

#627 Fix position of actions when repeatedly opened
  src/components/Actions/Actions.vue
Labels: 4. to release, backport-request, bug, feature: actions

#625 Fix different height of actions with custom icon
  src/components/Actions/Actions.vue
Labels: 3. to review, bug, feature: actions, papercut

#630 Mark PopoverMenu component as deprecated
  src/components/PopoverMenu/PopoverMenu.vue
Labels: 3. to review, feature: popovermenu

#635 Fix small issues with actions layout in sidebar in compact mode
  src/components/AppSidebar/AppSidebar.vue
Labels: 3. to review, backport-request, bug, design, feature: app-sidebar

#638 Fix colorpicker docs
  src/components/ColorPicker/ColorPicker.vue
Labels: 3. to review, feature: documentation

#639 Only set the width when tags wrap is actually available
  src/components/Multiselect/Multiselect.vue
Labels: 3. to review, backport-request, bug

#648 Forward listeners to V-Popover
  src/components/Popover/Popover.vue
Labels: 3. to review

#647 Forward slots to vue2-datepicker
  src/components/DatetimePicker/DatetimePicker.vue
Labels: 3. to review

#654 @nextcloud/vue
  package-lock.json
  package.json
Labels: 3. to review

#656 Fix spacer order
  src/components/AppNavigationSpacer/AppNavigationSpacer.vue
Labels: 3. to review, bug, design, feature: app-navigation

#655 Fix icon sizing
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 3. to review, bug, design, feature: app-navigation

#657 Add documentation for development setup
  README.md
Labels: 3. to review, enhancement

#658 Prevent app nav spaacer from shrinking
  src/components/AppNavigationSpacer/AppNavigationSpacer.vue
Labels: 3. to review, bug, design, feature: app-navigation

#659 Move to browserslist global config
  .babelrc.js
  .browserslistrc
  babel.config.js
  package-lock.json
  package.json
Labels: 3. to review, bug, configuration

#661 Forward action class to single action element
  src/components/Actions/Actions.vue
Labels: 3. to review, backport-request, bug, feature: actions

#666 [stable0-12] Move to browserslist global config
  .babelrc.js
  .browserslistrc
  babel.config.js
  package-lock.json
  package.json
Labels: 3. to review, configuration

#665 Add appsidebar close button unique class
  src/components/AppSidebar/AppSidebar.vue
Labels: 3. to review, backport-request, feature: app-sidebar

#672 fix package rename
  README.md
Labels: 3. to review

#670 Use @nextcloud/browserslist-config
  package-lock.json
  package.json
Labels: 3. to review

#673 fix package rename in docs
  docs/directives.md
  docs/index.md
  styleguide.config.js
Labels: 3. to review

#676 [stable0-12] Migrate to v-click-outside
  package-lock.json
  package.json
  src/components/Actions/Actions.vue
  src/components/AppNavigationItem/AppNavigationItem.vue
  src/components/AppNavigationSettings/AppNavigationSettings.vue
  src/components/Avatar/Avatar.vue
Labels: 3. to review, bug

#674 [stable0-12] Fix/@nextcloud/browserslist config
  package-lock.json
  package.json
Labels: 3. to review, configuration

#679 Mark dependencies as webpack externals
  package-lock.json
  package.json
  webpack.common.js
Labels: 3. to review, configuration, dependencies

#681 Enhance styleguide config
  styleguide.config.js
Labels: 3. to review, feature: documentation

#677 Fix Actions click outside
  src/components/Actions/Actions.vue
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 3. to review, backport-request, bug, feature: actions

#683 Fix Actions click outside
  src/components/Actions/Actions.vue
  src/components/AppNavigationItem/AppNavigationItem.vue
  src/components/Avatar/Avatar.vue
Labels: 3. to review, bug, feature: actions

#682 Fix ActionLink docs
  src/components/ActionLink/ActionLink.vue
Labels: 3. to review, feature: actions, feature: documentation

#684 Add netlify logo
  README.md
  docs/index.md
Labels: 3. to review

#686 Allow to replace default actions icon of appNavigationItem
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 4. to release, bug, feature: app-navigation

#687 fix badge
  README.md
Labels: 4. to release

#688 fix action's long-text style
  src/assets/action.scss
Labels: 4. to release, backport-request, design, feature: actions

#690 improve docs for undo
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 3. to review, enhancement, feature: app-navigation, feature: documentation

#703 fix package rename
  docs/index.md
Labels: 3. to review
