Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2019-07, with the labels that each got.

#448 Add updateTabs function to appSidebar
  src/components/AppSidebar/AppSidebar.vue
Labels: 3. to review, enhancement, feature: app-sidebar

#446 Fix actions white background
  src/assets/variables.scss
  src/components/Actions/Actions.vue
  src/components/Modal/Modal.vue
Labels: 3. to review, design

#451 Add AppSidebar compact mode
  package-lock.json
  src/assets/variables.scss
  src/components/Actions/Actions.vue
  src/components/AppNavigationItem/AppNavigationItem.vue
  src/components/AppSidebar/AppSidebar.vue
Labels: 4. to release, enhancement, feature: app-sidebar

#471 Fix actions documentation
  src/assets/action.scss
  src/components/ActionButton/ActionButton.vue
  src/components/ActionLink/ActionLink.vue
  src/components/Actions/Actions.vue
Labels: 3. to review

#472 Fix actioninput event and disabled styling
  src/components/ActionCheckbox/ActionCheckbox.vue
Labels: 3. to review, feature: actions

#473 Fix actionInput margins
  src/components/ActionInput/ActionInput.vue
Labels: 3. to review, bug, design, feature: actions

#474 Add actions menu margin
  src/components/Actions/Actions.vue
Labels: 3. to review, design, feature: actions, papercut

#468 AppNavigationItem extensions necessary for talk.
  src/components/AppNavigationCounter/AppNavigationCounter.vue
  src/components/AppNavigationCounter/index.js
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 4. to release, enhancement, feature: app-navigation

#477 Fix AppNavigationCounter export
  src/components/index.js
Labels: 3. to review, bug

#501 Allow to bind attributes to the ActionInput timepicker if present
  src/components/ActionInput/ActionInput.vue
Labels: 3. to review, enhancement, feature: actions

#500 Also allow value on checkbox
  src/components/ActionButton/ActionButton.vue
  src/components/ActionCheckbox/ActionCheckbox.vue
Labels: 3. to review, enhancement, feature: actions

#502 Focus proper action on mouse move instead of removing focus
  src/components/Actions/Actions.vue
Labels: 3. to review, accessibility, feature: actions

#503 Bind attrs to textarea and input as well and add actioninput docs
  src/components/ActionInput/ActionInput.vue
  src/components/ActionTextEditable/ActionTextEditable.vue
  styleguide/assets/additional.scss
Labels: 3. to review, enhancement, feature: actions

#504 Add and edit placeholder docs for actionInput
  src/components/ActionInput/ActionInput.vue
Labels: 3. to review, enhancement, feature: actions
