Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2019-01, with the labels that each got.

#193 Datepicker dark mode
  .gitignore
  .stylelintignore
  package-lock.json
  package.json
  src/assets/iconfont/README.md
  src/assets/iconfont/arrow-left-double.svg
  src/assets/iconfont/arrow-left.svg
  src/assets/iconfont/arrow-right-double.svg
  src/assets/iconfont/arrow-right.svg
  src/components/DatetimePicker/index.scss
  webpack.common.js
Labels: 4. to release, design, enhancement

#205 Bump eslint-suite and move away from eslint-plugin-vue beta
  package-lock.json
  package.json
Labels: 3. to review, configuration

#206 Fix default translated app nav settings title
  src/components/AppNavigationSettings/AppNavigationSettings.vue
Labels: 3. to review, bug

#209 toggleCollapse as default action for collapsible
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 3. to review, enhancement

#211 Fix action component breaking global tabbability
  src/components/Action/Action.vue
Labels: 4. to release, bug, design, feature: action, high, regression
