Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2020-07, with the labels that each got.

#1178 release 2.2.0
  package-lock.json
  package.json
Labels: 3. to review

#1176 reduce indentation of the sub-levels
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 3. to review, design, enhancement, feature: app-navigation

#1188 Add EmojiPicker Component
  l10n/messages.pot
  package-lock.json
  package.json
  src/components/EmojiPicker/EmojiPicker.vue
  src/components/EmojiPicker/index.js
Labels: 3. to review, enhancement, feature: emoji picker

#1217 Fix actions single border radius
  src/components/Actions/Actions.vue
Labels: 4. to release, bug, design, feature: actions

#1218 Fix progressbar validators
  src/components/ProgressBar/ProgressBar.vue
Labels: 3. to review, bug

#1148 Enh/active hover focus highlight
  src/components/AppNavigationItem/AppNavigationItem.vue
  styleguide/assets/variables.css
Labels: 4. to release, bug

#1240 Fix missing icons in avatar popover menu
  src/components/PopoverMenu/PopoverMenuItem.vue
Labels: 3. to review, bug, feature: avatar

#1241 Add missing OC.config for @nextcloud-router
  styleguide/global.requires.js
Labels: 3. to review, bug, feature: documentation

#1242 Add release manual to readme
  README.md
Labels: 3. to review
