Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2020-02, with the labels that each got.

#844 Only fire Multiselect input function once
  .github/workflows/npm-test.yml
  .gitignore
  package-lock.json
  package.json
  src/components/Multiselect/Multiselect.vue
  tests/.eslintrc.js
  tests/setup.js
  tests/unit/components/Multiselect/Multiselect.spec.js
Labels: 3. to review, bug, configuration

#849 Adjust tests syntax & formatting
  .github/workflows/npm-build-lint.yml
  .github/workflows/npm-publish.yml
  .github/workflows/npm-test.yml
Labels: 3. to review

#860 Switch month and year arrow icons
  src/components/DatetimePicker/index.scss
Labels: 3. to review, bug, design

#854 Add gettext-based translations
  .eslintrc.js
  .github/workflows/l10n.yml
  .github/workflows/transifex.yml
  .npmignore
  build/extract-l10n.js
  l10n/messages.pot
  package-lock.json
  package.json
  src/components/AppNavigationSettings/AppNavigationSettings.vue
  src/components/AppSidebar/AppSidebar.vue
  src/components/ColorPicker/ColorPicker.vue
  src/components/Modal/Modal.vue
  src/components/Multiselect/Multiselect.vue
  src/components/MultiselectTags/MultiselectTags.vue
  src/l10n.js
  src/mixins/l10n.js
  tests/setup.js
  webpack.common.js
Labels: 3. to review

#878 Fix missing OC.getLanguage() in docs
  styleguide/global.requires.js
Labels: 3. to review, bug
