Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2020-03, with the labels that each got.

#896 Fix appnavigationitem's active state
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 3. to review, bug

#898 Update npm publish node version and syntax
  .github/workflows/npm-publish.yml
Labels: 3. to review

#902 Don't throw error for users without email adress
  src/components/Avatar/Avatar.vue
Labels: 3. to review, bug, feature: avatar

#922 Fix dependencies audit
  package-lock.json
Labels: 3. to review, high, security

#923 Fix modal slideshow translation import
  src/components/Modal/Modal.vue
Labels: 3. to review, bug, feature: modal

#924 Force single multiselect value to be shown when the input is not active
  src/components/Multiselect/index.scss
Labels: 3. to review, bug

#887 Fix forceMenu for one action item
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 4. to release, enhancement

#651 add SettingsSection component
  src/assets/iconfont/info.svg
  src/components/SettingsSection/SettingsSection.vue
  src/components/SettingsSection/index.js
  src/components/index.js
Labels: 3. to review, component

#938 Fix audit and dependencies
  .eslintrc.js
  Makefile
  package-lock.json
  package.json
  src/components/Avatar/Avatar.vue
  styleguide/global.requires.js
Labels: 3. to review, dependencies, security

#937 Add ability to set a custom aria-label value for the actions menu button
  src/components/ActionButton/ActionButton.vue
  src/components/ActionLink/ActionLink.vue
  src/components/ActionRouter/ActionRouter.vue
  src/components/Actions/Actions.vue
  src/mixins/actionText.js
Labels: 3. to review, accessibility

#948 Fix actions aria labels
  l10n/messages.pot
  src/components/Actions/Actions.vue
Labels: 3. to review, accessibility, bug

#949 Use main as appContent
  src/components/AppContent/AppContent.vue
Labels: 3. to review, accessibility, feature: app-content

#951 fix aria-controls
  src/components/Actions/Actions.vue
Labels: 3. to review, accessibility, feature: actions

#952 Fix the validate slots function
  src/utils/ValidateSlot.js
Labels: 3. to review, bug

#954 Fix opening Actions menu
  src/components/Actions/Actions.vue
Labels: 3. to review, bug

#960 Comply to server's more icon
  src/assets/iconfont/more.svg
Labels: 3. to review, design

#913 Add breadcrumb component
  package-lock.json
  package.json
  src/assets/iconfont/breadcrumb.svg
  src/components/Breadcrumb/Breadcrumb.vue
  src/components/Breadcrumb/index.js
  src/components/Breadcrumbs/Breadcrumbs.vue
  src/components/Breadcrumbs/index.js
  src/components/index.js
  styleguide.config.js
  styleguide/assets/variables.css
Labels: 3. to review, component, feature: breadcrumbs

#962 Use breadcrumb component for hidden actions
  src/components/Breadcrumb/Breadcrumb.vue
  src/components/Breadcrumbs/Breadcrumbs.vue
Labels: 3. to review, bug, feature: breadcrumbs

#974 We don't need an intermediate data & watcher for Actions open state
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 3. to review, feature: actions
