Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2020-11, with the labels that each got.

#1525 Fix action text margin for long texts
  src/assets/action.scss
Labels: 4. to release, bug, design

#1543 Fix menu font for apps
  src/assets/action.scss
Labels: 3. to review, backport-request, bug

#1548 Bump cypress github-action to v2
  .github/workflows/cypress.yml
Labels: 4. to release, dependencies

#1504 Fix RichEditor rendering of unknown mention, undefined checks and fix default value init
  l10n/messages.pot
  src/components/RichContenteditable/RichContenteditable.vue
  src/mixins/richEditor/index.js
Labels: 3. to review, bug, feature: rich-contenteditable

#1555 Add tooltips in app sidebar header
  src/components/AppSidebar/AppSidebar.vue
Labels: 3. to review, enhancement

#1558 Revert "Also set Modal height/width to allow children to define their height/width and not only max-height/width"
  src/components/Modal/Modal.vue
Labels: 3. to review, bug, feature: modal, regression

#1570 Fix rich-contenteditor default value init and small code cleanup
  src/components/RichContenteditable/RichContenteditable.vue
Labels: 3. to review, bug, feature: rich-contenteditable

#1580 Proxy avatar to fixed image in the documentation
  package.json
  styleguide.config.js
  styleguide/global.requires.js
Labels: 3. to review, bug, feature: documentation

#1515 Improve testability + small code changes of AppSideBarTabs
  src/components/AppSidebar/AppSidebarTabs.vue
  tests/unit/components/AppSidebar/AppSidebarTabs.spec.js
Labels: 3. to review, feature: app-sidebar

#1583 Fix labelledby in tab section
  src/components/AppSidebarTab/AppSidebarTab.vue
Labels: 3. to review, bug

#1566 Remove sidebar actions slot max height
  src/components/AppSidebar/AppSidebar.vue
Labels: 3. to review, enhancement, feature: app-sidebar

#1584 Fix contenteditable state ad first load
  src/components/RichContenteditable/RichContenteditable.vue
Labels: 3. to review, bug

#1576 Fix action button text for long translations
  src/assets/action.scss
Labels: 3. to review, bug, design

#1277 AppNavigationItem improved editing mode and AppNavigationNewItem component
  src/components/AppNavigationItem/AppNavigationItem.vue
  src/components/AppNavigationItem/AppNavigationNewItem.vue
  src/components/AppNavigationItem/InputConfirmCancel.vue
Labels: 3. to review, enhancement, feature: app-sidebar

#1587 Allow disabling the avatar menu
  src/components/Avatar/Avatar.vue
Labels: 3. to review, enhancement

#1596 Add notes about styleguide command in README
  README.md
Labels: 3. to review

#1586 Remote semantics of h6 in user bubble
  src/components/UserBubble/UserBubble.vue
Labels: 3. to review, accessibility, bug

#1585 Set navigation role and aria label on app navigation
  src/components/AppNavigation/AppNavigation.vue
Labels: 3. to review, accessibility, enhancement

#1592 Richcontenteditable: bind event listeners
  src/components/RichContenteditable/RichContenteditable.vue
Labels: 3. to review, feature: rich-contenteditable

#1597 Do not check l10n comments
  .github/workflows/l10n.yml
  build/extract-l10n.js
  l10n/messages.pot
Labels: 3. to review, enhancement

#1599 Aria-expanded must be a false string, not absent
  src/components/Actions/Actions.vue
  src/components/AppNavigationToggle/AppNavigationToggle.vue
Labels: accessibility, bug

#1598 Remove conflict orig files
  .github/workflows/l10n.yml.orig
  l10n/messages.pot.orig
Labels: 3. to review, bug

#1605 Add changelog file
  .gitignore
  CHANGELOG.md
  README.md
Labels: 3. to review, technical debt

#1578 Add ListItemIcon component
  src/components/ListItemIcon/ListItemIcon.vue
  src/components/ListItemIcon/index.js
  src/components/Multiselect/AvatarSelectOption.vue
  src/components/Multiselect/Multiselect.vue
  src/components/index.js
Labels: 3. to review, enhancement, feature: list-item-icon, feature: multiselect

#1579 Fix default multiselect height
  src/components/ListItemIcon/ListItemIcon.vue
  src/components/Multiselect/Multiselect.vue
  src/components/Multiselect/index.scss
Labels: 3. to review, bug, design, feature: multiselect

#1616 Bump cypress github-action to v2
  .github/workflows/cypress.yml
Labels: 3. to review
