Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2021-08, with the labels that each got.

#2150 Fix typo on registering the directive
  docs/directives.md
Labels: 3. to review, feature: tooltip

#2151 Add a hint about the tooltip directive
  src/components/RichContenteditable/RichContenteditable.vue
Labels: 3. to review, feature: rich-contenteditable, feature: tooltip

#2159 Check that userId is defined before querying
  src/mixins/userStatus.js
Labels: bug, feature: list-item-icon

#2160 Use new named slot syntax
  src/components/ActionButton/ActionButton.vue
  src/components/Actions/Actions.vue
  src/components/AppContent/AppContent.vue
  src/components/AppNavigationCaption/AppNavigationCaption.vue
  src/components/AppNavigationIconBullet/AppNavigationIconBullet.vue
  src/components/AppNavigationItem/AppNavigationItem.vue
  src/components/AppNavigationToggle/AppNavigationToggle.vue
  src/components/AppSidebar/AppSidebar.vue
  src/components/Avatar/Avatar.vue
  src/components/Breadcrumbs/Breadcrumbs.vue
  src/components/DatetimePicker/DatetimePicker.vue
  src/components/Multiselect/Multiselect.vue
  src/components/MultiselectTags/MultiselectTags.vue
  src/components/Popover/Popover.vue
  src/components/SettingsSelectGroup/SettingsSelectGroup.vue
  src/components/UserBubble/UserBubble.vue
Labels: technical debt

#2126 standardize modal sizes
  src/components/Modal/Modal.vue
Labels: enhancement, 3. to review, design, feature: modal, breaking

#2170 add an additional Modal size
  src/components/Modal/Modal.vue
Labels: 3. to review, feature: modal

#2181 Fix backwards navigation for listitem component
  src/components/ListItem/ListItem.vue
Labels: bug, 3. to review

#2186 Simplify exports
  src/components/index.js
  src/directives/index.js
  src/mixins/index.js
Labels: 3. to review

#2187 set the settings modal size to large
  src/components/AppSettingsDialog/AppSettingsDialog.vue
Labels: enhancement, 3. to review, design, feature: modal, feature: settings

#2183 v4.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 2. developing
