Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2021-03, with the labels that each got.

#1733 Allow to inject preloaded user statuses
  src/components/Avatar/Avatar.vue
Labels: 3. to review, bug, enhancement, feature: avatar

#1734 Add a container property to popup components
  src/components/AppSettingsDialog/AppSettingsDialog.vue
  src/components/Avatar/Avatar.vue
  src/components/EmojiPicker/EmojiPicker.vue
  src/components/Modal/Modal.vue
Labels: 3. to review, enhancement

#1741 Fix ActionButton icon slot
  src/components/ActionButton/ActionButton.vue
Labels: 3. to review, bug

#1718 Improve multiselect tag
  src/components/Multiselect/index.scss
Labels: 4. to release, enhancement

#1753 Render the first action icon slot if single action
  src/components/Actions/Actions.vue
  styleguide.config.js
Labels: 3. to review, bug, feature: actions

#1744 Fix formattedOptions var in multiselect docs
  src/components/Multiselect/Multiselect.vue
Labels: 3. to review, bug, feature: documentation

#1757 Actions forward focus and blur events on trigger
  src/components/Actions/Actions.vue
Labels: 3. to review, enhancement

#1761 Fix actions dropdown focus timing
  src/components/Actions/Actions.vue
  src/components/Popover/Popover.vue
Labels: 4. to release, bug

#1777 Fix AutoApprove Action
  .github/workflows/dependabot-approve-merge.yml
Labels: 3. to review, technical debt

#1771 Allow last crumb to shrink if all crumbs collapsed
  src/components/Breadcrumb/Breadcrumb.vue
  src/components/Breadcrumbs/Breadcrumbs.vue
Labels: 3. to review, bug, feature: breadcrumbs

#1770 Fix Settings css
  src/components/SettingsSection/SettingsSection.vue
Labels: 3. to review, design, papercut

#1787 Fix multiselect listitemicon docs
  src/components/Multiselect/Multiselect.vue
Labels: 3. to review, bug, feature: documentation, feature: multiselect

#1769 Update AppNavigationCounter styles
  src/components/AppNavigationCounter/AppNavigationCounter.vue
Labels: 3. to review, feature: app-navigation, technical debt

#1767 Fix compact sidebar subtitle not visible
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar-compact.visual.js/AppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_none-editable_true-base.png
  src/components/AppSidebar/AppSidebar.vue
Labels: 4. to release, backport-request, bug, feature: app-sidebar

#1775 Minimize bundled translations
  src/l10n.js
  webpack.common.js
Labels: 3. to review, technical debt

#1783 Bump @nextcloud/eslint-config and related packages
  package-lock.json
  package.json
  src/components/DatetimePicker/DatetimePicker.vue
  src/components/Multiselect/Multiselect.vue
  src/components/PopoverMenu/PopoverMenuItem.vue
Labels: 3. to review, dependencies

#1789 Fix compact sidebar subtitle not visible, backport to stable2
  src/components/AppSidebar/AppSidebar.vue
Labels: 3. to review, feature: app-sidebar

#1776 Fix translation extraction
  build/extract-l10n.js
  l10n/messages.pot
  src/components/AppSidebar/AppSidebar.vue
  src/components/SettingsInputText/SettingsInputText.vue
  src/components/SettingsSection/SettingsSection.vue
Labels: 3. to review, papercut, technical debt

#1806 Add icon slot to emptycontent
  src/components/EmptyContent/EmptyContent.vue
Labels: 3. to review, enhancement, feature: emptycontent

#1807 Ensure that crumbs to hide have correct class
  src/components/Breadcrumbs/Breadcrumbs.vue
Labels: 3. to review, bug, feature: breadcrumbs
