Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2021-05, with the labels that each got.

#1911 Remove AppNavigationItem flex order for AppNavigationCaption
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 3. to review, bug, feature: app-navigation

#1917 Fix datepicker overflow when week numbers are shown
  src/components/DatetimePicker/DatetimePicker.vue
  src/components/DatetimePicker/index.scss
Labels: bug, feature: datepicker

#1921 Allow to append datepicker to body
  src/components/DatetimePicker/DatetimePicker.vue
  src/components/DatetimePicker/index.scss
Labels: 3. to review, bug

#1894 Add disabled state to RichContenteditable and clean not-working v-model
  src/components/RichContenteditable/RichContenteditable.vue
Labels: 3. to review, enhancement, feature: rich-contenteditable

#1914 Add proper opening/opened/closing/closed events & fix events docs
  src/components/AppSidebar/AppSidebar.vue
Labels: 3. to review, backport-request, enhancement, feature: app-sidebar

#1927 Correctly align md icon in ActionRouter component
  src/assets/action.scss
Labels: bug, feature: actions

#1912 Fix counter margin
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 3. to review, bug, regression

#1930 Wrap icon span in icon slot for ActionButton
  src/components/ActionButton/ActionButton.vue
Labels: feature: actions

#1938 Allow material design icon in breadcrumb
  src/components/Breadcrumb/Breadcrumb.vue
  src/components/Breadcrumbs/Breadcrumbs.vue
Labels: 3. to review, design, enhancement, feature: breadcrumbs

#1939 Allow material design icons in AppSidebarTab
  src/components/AppSidebar/AppSidebar.vue
  src/components/AppSidebar/AppSidebarTabs.vue
  src/components/AppSidebarTab/AppSidebarTab.vue
Labels: 3. to review, feature: app-sidebar

#1934 Prevent overflow of action-link in Firefox
  src/assets/action.scss
Labels: 3. to review, bug, feature: actions

#1854 Make avatar menu focusable with keyboard
  l10n/messages.pot
  src/components/Avatar/Avatar.vue
Labels: 4. to release, accessibility, backport-request, enhancement

#1966 Fix md icon size in ActionInput
  src/components/ActionInput/ActionInput.vue
Labels: 3. to review, bug, feature: actions

#1967 Fix first and last action input padding
  src/components/ActionInput/ActionInput.vue
Labels: 3. to review, bug, design, feature: actions

#1971 Add timestamp tooltip
  src/components/AppSidebar/AppSidebar.vue
Labels: 4. to release, backport-request

#1984 3.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1983 Delay all tooltips
  src/directives/Tooltip/index.js
Labels: 3. to review, enhancement
