Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2021-11, with the labels that each got.

#2343 Fix the space between navigation icon and label
  src/components/AppNavigationItem/AppNavigationItem.vue
  src/components/AppNavigationSettings/AppNavigationSettings.vue
Labels: enhancement, feature: app-navigation

#2349 Update npm and node engines versions
  package.json
Labels: dependencies

#2374 Change background style target for tab icons
  src/components/AppSidebar/AppSidebarTabs.vue
Labels: bug, 3. to review
