Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2021-09, with the labels that each got.

#2197 Improve modal and appsettingsdialog docs
  src/components/AppSettingsDialog/AppSettingsDialog.vue
  src/components/Modal/Modal.vue
Labels: enhancement, 3. to review, design, feature: modal, feature: settings

#2208 Add outlined counter
  src/components/CounterBubble/CounterBubble.vue
  src/components/ListItem/ListItem.vue
Labels: enhancement, 3. to review, component, design

#2219 Make timestamp of unread msg not bold
  src/components/ListItem/ListItem.vue
Labels: enhancement, 3. to review

#2220 Disable actions when the only action is disabeld
  src/components/Actions/Actions.vue
Labels: bug, 3. to review, feature: actions

#2225 Do not duplicate character in Highlight directive, only highlight first match occurence
  src/components/Highlight/Highlight.vue
  src/utils/FindRanges.js
  tests/unit/components/Highlight/Highlight.spec.js
  tests/unit/utils/FindRanges.spec.js
Labels: bug, 3. to review, feature: multiselect

#2229 Don't rely on Vue.prototype.t and properly extract all strings
  docs/index.md
  l10n/messages.pot
  src/components/AppContent/AppDetailsToggle.vue
  src/components/AppNavigationItem/InputConfirmCancel.vue
  src/components/AppNavigationToggle/AppNavigationToggle.vue
  src/components/AppSettingsDialog/AppSettingsDialog.vue
  src/components/DatetimePicker/DatetimePicker.vue
  src/components/RichContenteditable/RichContenteditable.vue
  src/components/SettingsSelectGroup/SettingsSelectGroup.vue
  styleguide/global.requires.js
Labels: 3. to review, configuration, technical debt, l10n

#2236 Fix empty user bubble
  src/components/UserBubble/UserBubble.vue
  src/components/UserBubble/UserBubbleDiv.vue
  styleguide.config.js
Labels: bug, 3. to review, regression, backport-request, feature: userbubble

#2249 Revert "Bump linkifyjs from 2.1.9 to 3.0.0"
  package-lock.json
  package.json
Labels: 3. to review

#2252 Stop filtering Actions in $slots
  src/components/Actions/Actions.vue
Labels: backport-request

#2256 3.10.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release

#2250 Add nofollow to tell search engines that links are not endorsed
  src/components/ActionLink/ActionLink.vue
  src/components/ActionRouter/ActionRouter.vue
  src/components/Actions/Actions.vue
  src/components/PopoverMenu/PopoverMenuItem.vue
  src/mixins/richEditor/index.js
Labels: 3. to review

#2274 address feedback on modal sizes
  src/components/Modal/Modal.vue
Labels: enhancement, 3. to review, design, feature: modal

#2217 Allow material design icons for appnavigationitem
  l10n/messages.pot
  src/components/AppNavigationItem/AppNavigationItem.vue
  src/components/AppNavigationSettings/AppNavigationSettings.vue
  src/components/AppSidebar/AppSidebar.vue
Labels: 3. to review, feature: app-navigation, design, backport-request

#2275 Unify linkify usage, move to linkify-string
  package-lock.json
  package.json
  src/components/AppSidebar/AppSidebar.vue
  src/directives/Linkify/index.js
  src/mixins/richEditor/index.js
  src/utils/Linkify.js
Labels: 3. to review, dependencies, feature: rich-contenteditable

#2289 Fix missing icon
  src/components/PopoverMenu/PopoverMenuItem.vue
Labels: bug, 3. to review, backport-request

#2288 V4.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
