Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2021-07, with the labels that each got.

#2084 4.0.3
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#2085 Simplify release process
  README.md
Labels: 3. to review

#2099 Fix videoplayer controls in viewer
  src/components/Modal/Modal.vue
Labels: 3. to review, design, enhancement

#2095 Add timezone picker
  l10n/messages.pot
  package-lock.json
  package.json
  resources/timezones/README.md
  resources/timezones/update-zones.py
  resources/timezones/zones.json
  src/components/TimezonePicker/TimezonePicker.vue
  src/components/TimezonePicker/index.js
  src/components/TimezonePicker/timezone.js
  src/components/TimezonePicker/timezoneDataProviderService.js
  src/utils/logger.js
Labels: 4. to release, enhancement

#2054 Fix sidebar title menu alignment
  cypress/snapshots/base/components/AppSidebar/AppSidebar.visual.js/AppSidebar.vue-subtitle_true-starred_false-compact_false-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar.visual.js/AppSidebar.vue-subtitle_true-starred_false-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar.visual.js/AppSidebar.vue-subtitle_true-starred_null-compact_false-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar.visual.js/AppSidebar.vue-subtitle_true-starred_null-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar.visual.js/AppSidebar.vue-subtitle_true-starred_true-compact_false-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/AppSidebar/AppSidebar.visual.js/AppSidebar.vue-subtitle_true-starred_true-compact_false-header_image-secondary_button-editable_true-base.png
  src/components/AppSidebar/AppSidebar.vue
Labels: 3. to review, design, feature: app-sidebar

#2100 Optionally make the DatetimePicker timezone-aware
  l10n/messages.pot
  src/components/DatetimePicker/DatetimePicker.vue
  src/components/TimezonePicker/TimezonePicker.vue
Labels: 4. to release, enhancement

#2122 Set default slideshowdelay to 5000 ms
  src/components/Modal/Modal.vue
Labels: 3. to review, design, enhancement
