Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2021-06, with the labels that each got.

#1993 Ensure the closed event is dispatched in AppSidebar
  src/components/AppSidebar/AppSidebar.vue
Labels: 3. to review, backport-request, enhancement, feature: app-sidebar

#1992 AppNavigationItem: hide utils if edit mode is active
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: 3. to review, backport-request, bug, design, feature: app-navigation

#2000 3.10.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release

#2005 Replace node-sass with sass
  package-lock.json
  package.json
  src/components/Actions/Actions.vue
Labels: 3. to review, dependencies

#1759 Resizable columns
  .eslintrc.js
  package-lock.json
  package.json
  src/components/AppContent/AppContent.vue
  src/components/AppContent/AppDetailsToggle.vue
Labels: 4. to release, breaking, enhancement, feature: app-content, feature: app-content-list

#1999 Fix alignment of loading spinner in avatar menu
  src/components/Avatar/Avatar.vue
Labels: 3. to review, backport-request, bug, regression

#2008 Fix documentation after #1759
  src/components/AppContent/AppContent.vue
  styleguide/global.requires.js
Labels: 3. to review, bug, feature: app-content, feature: documentation

#2001 Fix release documentation
  README.md
Labels: 3. to review, feature: documentation

#2013 Revert "Replace node-sass with sass"
  package-lock.json
  package.json
  src/components/Actions/Actions.vue
Labels: 3. to review, bug, high

#2015 Check slots on updated hook
  src/components/ListItem/ListItem.vue
Labels: 2. developing, bug, component

#2024 Fix flex order of AppNavigationCaption
  src/components/AppNavigationCaption/AppNavigationCaption.vue
Labels: 3. to review, bug, feature: app-navigation

#2007 4.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release, breaking

#2026 Do not use app-content-wrapper if no list is provided
  src/components/AppContent/AppContent.vue
Labels: 3. to review, bug, feature: app-content

#2030 set AppNavigation examples' width to 300px
  styleguide/assets/additional.scss
Labels: 3. to review

#2033 Fix settings navigation layout
  src/components/AppSettingsDialog/AppSettingsDialog.vue
Labels: 3. to review, design

#2028 Safely check the global appName and handle its inexistence
  src/components/AppContent/AppContent.vue
Labels: 3. to review, bug

#2032 4.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#2041 v4.0.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#2048 Fix AppContent mobile display
  src/components/AppContent/AppContent.vue
Labels: 3. to review, bug, design, feature: app-content

#2069 Add type=button attribute to buttons
  src/components/ActionButton/ActionButton.vue
  src/components/Actions/Actions.vue
  src/components/AppNavigationItem/AppNavigationIconCollapsible.vue
  src/components/AppNavigationNew/AppNavigationNew.vue
  src/components/AppNavigationSettings/AppNavigationSettings.vue
  src/components/ColorPicker/ColorPicker.vue
  src/components/Modal/Modal.vue
  src/components/PopoverMenu/PopoverMenuItem.vue
Labels: 3. to review, backport-request, bug

#2043 Fix ActionCaption layout
  src/components/ActionCaption/ActionCaption.vue
Labels: 3. to review, design, enhancement
