Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2022-04, with the labels that each got.

#2601 fix positioning of content text
  src/components/RichContenteditable/RichContenteditable.vue
Labels: bug, 3. to review, design

#2596 Ensure l10n check uses right node and npm version
  .github/workflows/l10n.yml
Labels: 3. to review

#2593 Update to webpack 5
  package-lock.json
  package.json
  webpack.prod.js
Labels: 4. to release, dependencies, technical debt

#2602 Cleanup tooltip and popover CSS
  src/components/Popover/Popover.vue
  src/directives/Tooltip/index.scss
Labels: 3. to review, feature: popovermenu, feature: actions, feature: tooltip

#2598 Migrate to @fontsource/roboto
  package-lock.json
  package.json
  tests/visual/components/AppSidebar/AppSidebarMixin.js
Labels: 3. to review, dependencies, technical debt

#2599 Migrate to @vue/vue2-jest
  package-lock.json
  package.json
  src/components/Actions/Actions.vue
  src/components/AppSidebar/AppSidebarTabs.vue
  src/components/VNodes/VNodes.vue
Labels: 3. to review, dependencies

#2559 Only show actions if actions given for breadcrumbs
  src/components/Breadcrumb/Breadcrumb.vue
Labels: 3. to review, feature: breadcrumbs

#2616 Remove unused dependency vue-visible
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#2617 Fix package issues by npm audit fix
  package-lock.json
Labels: 3. to review, dependencies, security

#2573 Fix visual issue of the settings tab in the documentation
  src/components/AppSidebar/AppSidebar.vue
Labels: bug, 3. to review, feature: documentation, feature: settings

#2618 Fix border radius for small progress bar
  src/components/ProgressBar/ProgressBar.vue
Labels: bug, 3. to review

#2622 Fix button disable state and reactivity
  src/components/Button/Button.vue
Labels: bug, 3. to review, accessibility, feature: button

#2586 Action button vue class
  src/components/Actions/Actions.vue
  src/components/Button/Button.vue
Labels: 3. to review

#2595 Update @nextcloud/stylelint-config to 2.1.2
  package-lock.json
  package.json
  src/assets/action.scss
  src/components/Actions/Actions.vue
  src/components/AppNavigationCaption/AppNavigationCaption.vue
  src/components/DatetimePicker/index.scss
  src/components/Modal/Modal.vue
Labels: 4. to release, dependencies, technical debt

#2610 don't give normal and large modals a fixed height
  src/components/Modal/Modal.vue
Labels: 3. to review

#2624 5.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#2628 Fix styleguide serve
  package-lock.json
  package.json
  styleguide.config.js
Labels: bug, 3. to review

#2633 Cleanup styleguide config
  package-lock.json
  package.json
  styleguide.config.js
Labels: 3. to review, dependencies

#2629 small cleanup of small modal size
  src/components/Modal/Modal.vue
Labels: enhancement, 4. to release, design

#2638 Fix lifecycle hook name in Avatar
  src/components/Avatar/Avatar.vue
Labels: bug, 4. to release

#2647 Do not lint during build
  package-lock.json
  package.json
  webpack.common.js
Labels: 3. to review, dependencies, configuration

#2650 Remove unused `isMobile` mixin from AppNavigationNewItem
  src/components/AppNavigationNewItem/AppNavigationNewItem.vue
Labels: 3. to review, component

#2662 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies
