Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2022-09, with the labels that each got.

#3142 Make the app content list 300px min
  src/components/NcAppContent/NcAppContent.vue
Labels: enhancement, 3. to review

#3140 Improve text fields
  src/components/NcInputField/NcInputField.vue
  src/components/NcPasswordField/NcPasswordField.vue
  src/components/NcTextField/NcTextField.vue
Labels: 3. to review

#3141 Simplify exports
  src/components/NcActionButton/index.js
  src/components/NcActionCaption/index.js
  src/components/NcActionCheckbox/index.js
  src/components/NcActionInput/index.js
  src/components/NcActionLink/index.js
  src/components/NcActionRadio/index.js
  src/components/NcActionRouter/index.js
  src/components/NcActionSeparator/index.js
  src/components/NcActionText/index.js
  src/components/NcActionTextEditable/index.js
  src/components/NcActions/index.js
  src/components/NcAppContent/index.js
  src/components/NcAppContentDetails/index.js
  src/components/NcAppContentList/index.js
  src/components/NcAppNavigation/index.js
  src/components/NcAppNavigationCaption/index.js
  src/components/NcAppNavigationCounter/index.js
  src/components/NcAppNavigationIconBullet/index.js
  src/components/NcAppNavigationItem/index.js
  src/components/NcAppNavigationNew/index.js
  src/components/NcAppNavigationNewItem/index.js
  src/components/NcAppNavigationSettings/index.js
  src/components/NcAppNavigationSpacer/index.js
  src/components/NcAppSettingsDialog/index.js
  src/components/NcAppSettingsSection/index.js
  src/components/NcAppSidebar/index.js
  src/components/NcAppSidebarTab/index.js
  src/components/NcAvatar/index.js
  src/components/NcBreadcrumb/index.js
  src/components/NcBreadcrumbs/index.js
  src/components/NcButton/index.js
  src/components/NcCheckboxRadioSwitch/index.js
  src/components/NcColorPicker/index.js
  src/components/NcContent/index.js
  src/components/NcCounterBubble/index.js
  src/components/NcDashboardWidget/index.js
  src/components/NcDashboardWidgetItem/index.js
  src/components/NcEmojiPicker/index.js
  src/components/NcEmptyContent/index.js
  src/components/NcHighlight/index.js
  src/components/NcInputField/index.js
  src/components/NcListItem/index.js
  src/components/NcListItemIcon/index.js
  src/components/NcLoadingIcon/index.js
  src/components/NcMultiselectTags/index.js
  src/components/NcNoteCard/index.js
  src/components/NcPasswordField/index.js
  src/components/NcPopover/index.js
  src/components/NcPopoverMenu/index.js
  src/components/NcProgressBar/index.js
  src/components/NcRichContenteditable/index.js
  src/components/NcSettingsInputText/index.js
  src/components/NcSettingsSection/index.js
  src/components/NcTextField/index.js
  src/components/NcTimezonePicker/index.js
  src/components/NcUserBubble/index.js
  src/components/NcVNodes/index.js
  src/functions/usernameToColor/index.js
Labels: 4. to release

#3143 Release v6.0.0-beta.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3091 Implement new container layout
  src/components/NcAppContent/NcAppContent.vue
  src/components/NcAppNavigation/NcAppNavigation.vue
  src/components/NcAppSidebar/NcAppSidebar.vue
  src/components/NcContent/NcContent.vue
Labels: enhancement, 3. to review, breaking

#3145 7.0.0-beta.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3147 Fix .active state of app list items
  src/components/NcListItem/NcListItem.vue
Labels: 3. to review, backport-request

#3149 Use events provided by floating-vue
  src/components/NcPopover/NcPopover.vue
Labels: 3. to review, feature: actions, backport-request

#3063 Add a native datetime picker
  src/components/NcActionInput/NcActionInput.vue
  src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
  src/components/NcDateTimePickerNative/index.js
  src/components/index.js
Labels: enhancement, 3. to review, component, feature: datepicker, backport-request

#3158 Fix spacing in app navigation and make the setting pill style
  src/components/NcAppNavigation/NcAppNavigation.vue
  src/components/NcAppNavigationNew/NcAppNavigationNew.vue
  src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue
Labels: bug, 3. to review, ui-refresh-feedback

#3136 Fix for border-radius being too large for 3-line entries like in Mail
  src/components/NcListItem/NcListItem.vue
Labels: enhancement, 3. to review, design, feature: app-content-list

#3081 Add related resources panel component
  l10n/messages.pot
  src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
  src/components/NcRelatedResourcesPanel/NcResource.vue
  src/components/NcRelatedResourcesPanel/index.js
  src/components/index.js
Labels: enhancement, 3. to review

#3165 Fix AppNavigationItem actions visibility
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review, feature: app-navigation, high, regression, backport-request

#3157 Fix actions positioning
  src/components/NcActions/NcActions.vue
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review, regression, backport-request, ui-refresh-feedback

#3168 Release v6.0.0-beta.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3174 Make NcMultiselect pixel perfect
  src/components/NcMultiselect/index.scss
Labels: bug, 3. to review, backport-request

#3173 Release v7.0.0-beta.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3172 Fix docs of NcAppNavigationItem with actions menu
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review, feature: documentation, backport-request

#3178 Right-align nav item utils
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review, design, backport-request

#3175 fix comments border-radius
  src/components/NcRichContenteditable/NcRichContenteditable.vue
Labels: 3. to review, ui-refresh-feedback

#2899 Button accessibility improvements
  .gitignore
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_none-secondary_none-editable_true-base.png
  src/components/NcButton/NcButton.vue
Labels: 4. to release, accessibility

#3186 Adjust appnavigation settings border radius
  src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue
Labels: bug, 3. to review, feature: app-navigation, design

#3192 Limit max width of the settings
  src/components/NcSettingsSection/NcSettingsSection.vue
Labels: 3. to review

#3200 Fix scrolling in styleguide
  styleguide/assets/additional.css
Labels: bug, 3. to review

#3197 Fix NcAppNavigationItem, pass correct boundaries-element NcActions
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: 3. to review, feature: app-navigation, regression

#3119 Use dark themed avatar on dark theme
  src/components/NcAvatar/NcAvatar.vue
Labels: 3. to review

#3202 Fix overwriting placeholder property in NcDatetimePicker
  l10n/messages.pot
  src/components/NcDatetimePicker/NcDatetimePicker.vue
Labels: bug, 3. to review

#3204 Fix loading avatar status
  src/components/NcAvatar/NcAvatar.vue
  webpack.config.js
Labels: bug, 3. to review

#3201 Fix active and focus frame
  src/components/NcInputField/NcInputField.vue
Labels: 3. to review, backport-request

#3189 Fix app navigation backdrop blur
  src/components/NcAppNavigation/NcAppNavigation.vue
Labels: 3. to review

#3191 Fix the NcPopoverMenu component
  src/components/NcPopoverMenu/NcPopoverMenu.vue
  src/components/NcPopoverMenu/NcPopoverMenuItem.vue
Labels: 3. to review

#3211 Release v7.0.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3212 Fix single action detection
  src/components/NcActions/NcActions.vue
Labels: bug, 3. to review, backport-request

#3225 Fix a word puzzle in NcDashboardWidget component
  l10n/messages.pot
  src/components/NcDashboardWidget/NcDashboardWidget.vue
Labels: 3. to review, backport-request

#3183 Improve using of native datetime picker
  src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
Labels: 3. to review

#3229 Release v7.0.0-beta.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3244 Fix avatar border color
  src/components/NcAvatar/NcAvatar.vue
Labels: bug, 3. to review, feature: avatar

#3250 Add proper margin to the counter
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review

#3252 Fix multiselect background color spilling outside the component
  src/components/NcMultiselect/index.scss
Labels: 3. to review, design

#3253 Fix NcEmptyContent used inside NcModal
  src/components/NcEmptyContent/NcEmptyContent.vue
Labels: bug, 3. to review, feature: modal, feature: emptycontent

#3236 Update design of related resources panel
  l10n/messages.pot
  src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
  src/components/NcRelatedResourcesPanel/NcResource.vue
  styleguide/global.requires.js
  tests/OC.js
Labels: 3. to review, design

#3235 Add gap between nav entry
  src/components/NcAppNavigation/NcAppNavigation.vue
Labels: enhancement, 3. to review

#3257 Release v7.0.0-beta.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release

#3230 Move the close button to the end of the content
  src/components/NcModal/NcModal.vue
Labels: bug, 3. to review

#3259 Mark resource button styles as important to fix styles in some contexts
  src/components/NcRelatedResourcesPanel/NcResource.vue
Labels: bug, 3. to review

#3247 v6.0.0 beta.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3256 Make app navigation settings pixel perfect-ish
  src/assets/variables.scss
  src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue
Labels: bug, 3. to review, design

#3245 Forward the autofocus attribute to input field component
  src/components/NcPasswordField/NcPasswordField.vue
  src/components/NcTextField/NcTextField.vue
Labels: enhancement

#3219 Allow opting out of automatic NcModal remounting
  src/components/NcModal/NcModal.vue
Labels: 3. to review, feature: modal, accessibility

#3266 Live refresh image and displayname based avatar on update
  src/components/NcAvatar/NcAvatar.vue
Labels: enhancement, 4. to release, feature: avatar

#3270 Add styleguide example for non-user avatar
  src/components/NcAvatar/NcAvatar.vue
Labels: enhancement, 3. to review

#3271 Fix initials color of new non-user avatars
  src/components/NcAvatar/NcAvatar.vue
Labels: bug, 3. to review, regression

#3272 Fix non-user avatar on complex background
  src/components/NcAvatar/NcAvatar.vue
Labels: bug, 3. to review, regression, design, feature: avatar

#3279 Release v7.0.0-beta.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3282 Fix unclickable text at the beginning of the inputfield
  src/components/NcInputField/NcInputField.vue
Labels: bug, 3. to review

#3277 Merge pre-releases changelog for v6
  CHANGELOG.md
Labels: 3. to review

#3286 Fix minor linting errors
  src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
Labels: 4. to release

#3288 fix NcAppNavigationItem, pass boundaries-element NcActions's prop as …
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review, feature: app-navigation, backport-request

#3283 Enables ESM Modules
  README.md
  cypress/plugins/index.js
  package.json
  resources/translations.js
  src/components/NcRichContenteditable/NcRichContenteditable.vue
  src/components/index.js
  src/functions/emoji/emoji.js
  src/functions/emoji/index.js
  src/functions/index.js
  src/index.js
  src/install.js
  styleguide.config.js
  webpack.config.js
Labels: enhancement, 3. to review, feature: emoji picker

#3261 Fix SCSS to CSS variable assignment
  src/components/NcAppContent/NcAppContent.vue
Labels: bug, 3. to review

#3296 Bump version to 7.0.0-beta.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3297 Fix alignment of NcAppNavigationCaption
  src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
Labels: 3. to review, feature: app-navigation, design

#3301 Fix: export missing NcProgressBar component
  src/components/index.js
Labels: bug, 3. to review

#3304 Make Viewer title h2
  src/components/NcModal/NcModal.vue
Labels: 3. to review, accessibility, backport-request

#3310 fix Avatar Size
  src/components/NcAvatar/NcAvatar.vue
Labels: 3. to review

#3312 Fix NcMultiselect height
  src/components/NcMultiselect/index.scss
Labels: bug, 3. to review, design

#3313 🔖 v7.0.0-beta.7
  package-lock.json
  package.json
Labels: 4. to release

#3311 Increase modal title breakpoint and prevent overflow
  src/components/NcModal/NcModal.vue
Labels: 3. to review, design, feature: modal

#3321 Use new slot syntax everywhere
  src/components/NcInputField/NcInputField.vue
  src/components/NcTextField/NcTextField.vue
Labels: 3. to review, technical debt
