Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2022-10, with the labels that each got.

#3329 Fix app content growing too wide
  src/components/NcAppContent/NcAppContent.vue
Labels: bug, 3. to review, regression

#3320 Add emits property to NcNativeDatetimePicker
  src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
Labels: 3. to review, feature: datepicker

#3324 Add advanced fields to color picker
  src/components/NcColorPicker/NcColorPicker.vue
Labels: enhancement, 4. to release, feature: colorpicker

#3350 Also use menuOpen state in NcAppNavigationItem
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 4. to release

#3343 Fix emoji picker and Popover no-Auto-Focus
  src/components/NcEmojiPicker/NcEmojiPicker.vue
  src/components/NcPopover/NcPopover.vue
Labels: 4. to release, feature: popovermenu, accessibility, feature: emoji picker

#3307 Fix contrast of maxcontrast text on blurred background
  src/components/NcAppNavigation/NcAppNavigation.vue
  src/components/NcListItem/NcListItem.vue
Labels: 3. to review, accessibility

#3355 v7.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release

#3347 use @nextcloud/focus-trap instead of focus-trap
  package-lock.json
  package.json
  src/components/NcModal/NcModal.vue
  src/components/NcPopover/NcPopover.vue
Labels: enhancement, 3. to review, high, accessibility, backport-request

#3364 7.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug, 3. to review

#3373 Export NcMentionBubble and NcAutoCompleteResult
  src/components/NcRichContenteditable/index.js
  src/components/index.js
Labels: enhancement, 3. to review, feature: rich-contenteditable

#3372 Fix empty content height in NcDashboardWidget in N in N in N
  src/components/NcDashboardWidget/NcDashboardWidget.vue
Labels: 3. to review

#3384 Allow to provide a custom palette to the ColorPicker
  src/components/NcColorPicker/NcColorPicker.vue
Labels: enhancement, 3. to review, feature: colorpicker

#3336 Add minlength and maxlength to text field
  src/components/NcPasswordField/NcPasswordField.vue
  src/components/NcTextField/NcTextField.vue
Labels: enhancement, 4. to release, feature: input-field

#3323 Add undo trailing icon
  src/components/NcTextField/NcTextField.vue
Labels: enhancement, 4. to release, feature: input-field

#3299 Forward ref of actions to inline actions
  src/components/NcActions/NcActions.vue
Labels: backport-request

#3366 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#3365 Updating lint-stylelint.yml workflow from template
  .github/workflows/lint-stylelint.yml
Labels: dependencies

#3401 Implement cron job to synchronise server styling
  .github/workflows/server-styling-update.yml
  styleguide/assets/additional.css
  styleguide/assets/close.svg
  styleguide/assets/default.css
  styleguide/assets/icons.css
  styleguide/assets/img/app-background.jpg
  styleguide/assets/server.css
Labels: 3. to review

#3407 Fix missing half-empty dashboard empty content view
  src/components/NcDashboardWidget/NcDashboardWidget.vue
Labels: bug, 3. to review, regression, backport-request, feature: dashboard
