Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2022-12, with the labels that each got.

#3539 Fix icon repeat and position for AppNavigationItem
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review, feature: app-navigation, regression

#3537 Scope global #content styles via extra class
  src/components/NcGuestContent/NcGuestContent.vue
Labels: bug, 3. to review, regression

#3532 Add button role for NcButton with href
  src/components/NcButton/NcButton.vue
Labels: bug, 3. to review, feature: actions

#3489 Add NcHeaderMenu
  src/components/NcHeaderMenu/NcHeaderMenu.vue
  src/components/NcHeaderMenu/index.js
  src/components/index.js
Labels: 4. to release, accessibility

#3530 Fix focus returning to top of page instead of actions toggle button
  src/components/NcActions/NcActions.vue
  src/components/NcPopover/NcPopover.vue
Labels: bug, 3. to review, feature: actions, accessibility

#3545 Fix jsdoc: Add missing documentation for events
  src/components/NcBreadcrumb/NcBreadcrumb.vue
  src/components/NcBreadcrumbs/NcBreadcrumbs.vue
  src/components/NcListItem/NcListItem.vue
Labels: enhancement, 4. to release, feature: documentation

#3511 Automated styling update from server
  styleguide/assets/default.css
  styleguide/assets/icons.css
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#3551 Increase input field border contrast
  src/components/NcInputField/NcInputField.vue
Labels: 3. to review, accessibility, feature: input-field

#3559 Revert "fix sidebar scrolling for small displays"
  src/components/NcAppSidebar/NcAppSidebarTabs.vue
Labels: 3. to review

#3572 Add more space for unread counter so its aligned with action menu
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review, design

#3517 Allow accessible labels for NcActionInput
  src/components/NcActionInput/NcActionInput.vue
Labels: enhancement, 4. to release, feature: actions, accessibility, feature: input-field

#3592 v7.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3597 Create `aria-label` for icon link
  src/components/NcSettingsSection/NcSettingsSection.vue
Labels: 3. to review

#3598 Fix appNavigationItem collapse labels
  l10n/messages.pot
  src/components/NcAppNavigationItem/NcAppNavigationIconCollapsible.vue
Labels: bug, 3. to review, accessibility

#3468 Allow spaces when autocompleting mentions
  src/components/NcRichContenteditable/NcRichContenteditable.vue
  src/mixins/richEditor/index.js
Labels: bug, 3. to review, backport-request, feature: rich-contenteditable
