Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2022-11, with the labels that each got.

#3405 Fix DateTimePicker example and translation
  l10n/messages.pot
  src/components/NcDatetimePicker/NcDatetimePicker.vue
Labels: bug, 4. to release, feature: datepicker, backport-request

#3410 Expand color picker width only when using advanced fields
  src/components/NcColorPicker/NcColorPicker.vue
Labels: 4. to release, feature: colorpicker

#3408 Fix password_policy fallback handling
  src/components/NcPasswordField/NcPasswordField.vue
Labels: bug, 4. to release, feature: input-field

#3402 Automated styling update from server
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar-compact.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_image-secondary_button-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_image-secondary_none-editable_false-base.png
  cypress/snapshots/base/components/NcAppSidebar/NcAppSidebar.visual.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_image-secondary_none-editable_true-base.png
  styleguide/assets/default.css
  styleguide/assets/icons.css
  styleguide/assets/server.css
Labels: 4. to release, dependencies

#3411 Fix dark themed color picker and use button component
  src/components/NcColorPicker/NcColorPicker.vue
Labels: bug, 4. to release, feature: colorpicker

#3404 Allow querying for resources with complex item ids
  src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
Labels: enhancement, 4. to release

#3444 fix sidebar scrolling for small displays
  src/components/NcAppSidebar/NcAppSidebarTabs.vue
Labels: bug, 4. to release, backport-request

#3454 Comment placeholder wording fix
  l10n/messages.pot
  src/components/NcRichContenteditable/NcRichContenteditable.vue
Labels: 3. to review, l10n

#3445 fix the size of the popper element
  src/components/NcActions/NcActions.vue
Labels: bug, 3. to review, backport-request

#3462 Widen container prop type passed to NcPopover
  src/components/NcActions/NcActions.vue
  src/components/NcAvatar/NcAvatar.vue
  src/components/NcEmojiPicker/NcEmojiPicker.vue
Labels: bug, enhancement, 3. to review, feature: popovermenu

#3367 Fix outdated variables
  src/components/NcActionInput/NcActionInput.vue
  src/components/NcActionTextEditable/NcActionTextEditable.vue
  src/components/NcAppNavigationItem/NcInputConfirmCancel.vue
  src/components/NcAppSidebar/NcAppSidebarTabs.vue
  src/components/NcButton/NcButton.vue
  src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
  src/components/NcListItemIcon/NcListItemIcon.vue
  src/components/NcNoteCard/NcNoteCard.vue
  src/components/NcRichContenteditable/NcAutoCompleteResult.vue
  src/components/NcRichContenteditable/NcRichContenteditable.vue
  src/components/NcSettingsInputText/NcSettingsInputText.vue
Labels: bug, 3. to review, technical debt

#3478 Define global focus trap
  package-lock.json
  package.json
  src/components/NcModal/NcModal.vue
  src/components/NcPopover/NcPopover.vue
  src/utils/focusTrap.js
Labels: bug, 3. to review, high

#3480 7.1.0-beta.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3485 Extend NcInputField props and forward $attrs to NcPasswordField and NcTextField
  src/components/NcInputField/NcInputField.vue
  src/components/NcPasswordField/NcPasswordField.vue
  src/components/NcTextField/NcTextField.vue
  src/components/index.js
  styleguide.config.js
Labels: enhancement, 4. to release, feature: input-field

#3487 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#3474 Bump @nextcloud/eslint-config from 8.1.2 to 8.1.3
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#3491 Fix value type for DateTimePickerNative
  src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
Labels: bug, 3. to review, feature: datepicker

#3502 Move loadState to data for better mockability
  src/components/NcPasswordField/NcPasswordField.vue
Labels: bug, 4. to release

#3503 7.1.0-beta.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3504 Finish emoji focus cleaning
  src/components/NcEmojiPicker/NcEmojiPicker.vue
  src/components/NcPopover/NcPopover.vue
Labels: 3. to review, technical debt

#3513 Fix multiselect checkmark and plus icon
  src/components/NcMultiselect/index.scss
Labels: bug, 3. to review

#3506 Make gap in NcAppNavigation consistent in nested lists
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review

#3515 release v7.1.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3435 Add accessible NcSelect and NcSelectTags components
  l10n/messages.pot
  package-lock.json
  package.json
  src/components/NcEllipsisedOption/NcEllipsisedOption.vue
  src/components/NcEllipsisedOption/index.js
  src/components/NcListItemIcon/NcIconSvgWrapper.vue
  src/components/NcListItemIcon/NcListItemIcon.vue
  src/components/NcMultiselect/NcMultiselect.vue
  src/components/NcMultiselectTags/NcMultiselectTags.vue
  src/components/NcSelect/NcSelect.vue
  src/components/NcSelect/index.js
  src/components/NcSelectTags/NcSelectTags.vue
  src/components/NcSelectTags/api.js
  src/components/NcSelectTags/index.js
  src/components/index.js
  styleguide.config.js
  styleguide/assets/server.css
  webpack.config.js
Labels: enhancement, 3. to review, feature: multiselect, accessibility

#3522 Release v7.1.0
  .github/workflows/changelog-generate.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release
