Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2022-03, with the labels that each got.

#2540 Fix error spam from buttons
  src/components/Button/Button.vue
Labels: bug, 4. to release, feature: button

#2536 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#2534 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#2535 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#2547 Fix error spam of icon only buttons part2
  src/components/Button/Button.vue
Labels: bug, 3. to review, regression, feature: button

#2554 Disallow secondary buttons
  src/components/Button/Button.vue
Labels: bug, 3. to review, technical debt

#2556 Pass in a boolean instead of a string in the 'wide' prop
  src/components/Button/Button.vue
Labels: bug, 3. to review, feature: documentation

#2557 Bugfix/fix button text margin
  src/components/Button/Button.vue
Labels: 3. to review, feature: button

#2562 Fix secondary button with old style as temporary solution
  src/components/Button/Button.vue
Labels: bug, 3. to review, feature: button

#2563 Inherit attrs and forward listeners in the emojipicker's popover
  src/components/EmojiPicker/EmojiPicker.vue
Labels: enhancement, 3. to review, component, feature: emoji picker

#2570 v5.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#2564 Fix the ProgressBar display in the documentation
  src/components/ProgressBar/ProgressBar.vue
Labels: bug, 3. to review, feature: documentation

#2583 Fix tertiary buttons hover feedback
  src/components/Button/Button.vue
Labels: bug, 3. to review

#2585 Add tertiary buttons with background and make them the default
  src/components/Button/Button.vue
Labels: 3. to review

#2589 Fix tertiary no background button color
  src/components/Button/Button.vue
Labels: bug, 3. to review

#2591 v5.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
