Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2022-02, with the labels that each got.

#2472 Add aria label to the ActionInput component
  src/components/ActionInput/ActionInput.vue
Labels: 3. to review, accessibility

#2483 AppNavigationItem.vue: updating of this.$slots
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: bug, 3. to review, feature: app-navigation, backport-request

#2486 Limit avatar request sizes to 64 and 512 pixel
  src/components/Avatar/Avatar.vue
Labels: 3. to review, feature: avatar

#2488 Bump version to v5.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#2492 Fix shrinking of last breadcrumb for narrow width
  src/components/Breadcrumb/Breadcrumb.vue
  src/components/Breadcrumbs/Breadcrumbs.vue
Labels: bug, 3. to review, feature: breadcrumbs

#2506 Change appearance of the slot "icon" at AppNavigationItem
  src/components/AppNavigationItem/AppNavigationItem.vue
Labels: bug, 3. to review, backport-request

#2366 Update Emoji picker to 10.2
  package-lock.json
  package.json
  src/components/EmojiPicker/EmojiPicker.vue
Labels: enhancement, 3. to review, feature: emoji picker

#2521 fix: imports from emoji-mart-vue-fast
  src/functions/emoji/emoji.js
Labels: 3. to review

#2491 Allow Breadcrumbs "to" prop to be an object
  src/components/Breadcrumb/Breadcrumb.vue
Labels: enhancement, 4. to release, feature: breadcrumbs

#2496 increase the small modal width
  src/components/Modal/Modal.vue
Labels: enhancement, 3. to review, design

#2516 Add button native type prop on <Button>
  src/components/Button/Button.vue
Labels: enhancement, 3. to review
