Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2023-05, with the labels that each got.

#4026 Adjust breadcrumb CSS to new html structure
  src/components/NcBreadcrumbs/NcBreadcrumbs.vue
Labels: 3. to review, feature: breadcrumbs

#4016 Add aria-hidden attr to the whole navigation depending on a sidebar state
  src/components/NcAppNavigation/NcAppNavigation.vue
Labels: 3. to review

#4029 v7.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#4027 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#4031 fix(NcRichContenteditable): Also quote ids containing a slash
  src/components/NcRichContenteditable/NcMentionBubble.vue
  src/mixins/richEditor/index.js
Labels: bug, 3. to review, feature: rich-contenteditable

#4035 fix(NcAppNavigation): fix flex element styles causing resizing sidebar
  src/components/NcAppNavigation/NcAppNavigation.vue
Labels: 3. to review, feature: app-navigation

#4036 fix: Avoid showing the reference list if no results were found
  src/components/NcRichText/NcReferenceList.vue
Labels: bug, 3. to review

#4039 fix: Fix regression to still display references
  src/components/NcRichText/NcReferenceList.vue
Labels: bug

#4043 fix(NcRichContenteditable): Fix avatar overlayed with empty space whe…
  src/components/NcRichContenteditable/NcAutoCompleteResult.vue
  src/components/NcRichContenteditable/NcRichContenteditable.vue
Labels: bug, 3. to review, backport-request, feature: rich-contenteditable

#4046 Fix regression of click-outside-options mixin not working since using `@vueuse`
  src/mixins/clickOutsideOptions/index.js
Labels: 4. to release, regression, backport-request

#4040 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#4062 chore(release): Release version to 7.11.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 2. developing

#4050 Automated styling update from server
  styleguide/assets/default.css
  styleguide/assets/server.css
Labels: 4. to release, dependencies

#4052 Migrate from deprecated title prop
  src/components/NcActionButton/NcActionButton.vue
  src/components/NcActionLink/NcActionLink.vue
  src/components/NcActionRouter/NcActionRouter.vue
  src/components/NcActionText/NcActionText.vue
  src/components/NcActionTextEditable/NcActionTextEditable.vue
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
  src/components/NcBreadcrumb/NcBreadcrumb.vue
  src/components/NcBreadcrumbs/NcBreadcrumbs.vue
  src/mixins/actionText.js
Labels: 3. to review

#4049 enh(NcActions): Readability
  src/assets/action.scss
  src/components/NcActionCheckbox/NcActionCheckbox.vue
  src/components/NcActionInput/NcActionInput.vue
  src/components/NcActionRadio/NcActionRadio.vue
  src/components/NcActionTextEditable/NcActionTextEditable.vue
  src/components/NcActions/NcActions.vue
Labels: 4. to release, feature: datepicker, feature: actions, feature: select, accessibility, feature: input-field

#4066 fix(NcSelect): Action input usage
  src/components/NcActionInput/NcActionInput.vue
  src/components/NcSelect/NcSelect.vue
Labels: bug, 4. to release, feature: actions, regression, feature: select

#4071 Emit event when NcAppContent list pane is resized
  src/components/NcAppContent/NcAppContent.vue
Labels: enhancement, 3. to review, feature: app-content

#4080 fix(styleguide): Fix URL replacement to not be 404
  styleguide.config.js
  styleguide/global.requires.js
Labels: bug, 3. to review

#4017 Use `NcActions` component for `NcAvatar`
  src/components/NcActions/NcActions.vue
  src/components/NcAvatar/NcAvatar.vue
Labels: 3. to review, feature: popovermenu, feature: actions, design, feature: avatar, technical debt

#4081 Remove deprecated popovermenu component
  src/components/NcPopoverMenu/NcPopoverMenu.vue
  src/components/NcPopoverMenu/NcPopoverMenuItem.vue
  src/components/NcPopoverMenu/index.js
  src/components/index.js
  styleguide.config.js
Labels: 3. to review, feature: popovermenu, breaking

#4083 Fix NcListItem wrong bold class
  src/components/NcListItem/NcListItem.vue
Labels: bug, 3. to review, backport-request, feature: list-item

#4082 Minor avatar cleanup
  src/components/NcAvatar/NcAvatar.vue
Labels: 3. to review, feature: avatar

#3866 Allow setting modal size when registering a custom picker component
  src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue
  src/components/NcRichText/NcReferencePicker/customPickerElements.js
Labels: enhancement, 3. to review, backport-request, feature: richtext

#4079 fix(NcSelect): Fix disabled state of NcSelect with dark mode
  src/components/NcSelect/NcSelect.vue
Labels: bug, 3. to review, feature: select, accessibility, backport-request

#4090 update sidebar to really take the whole space on mobile
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: bug, 3. to review, backport-request

#4088 Remove excludeClickOutsideClasses from clickOutsideOptions
  src/mixins/clickOutsideOptions/index.js
Labels: 3. to review, breaking

#4092 chore(release): Bump version to 7.11.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release

#4096 Remove deprecated `NcAppNavigationCounter` component
  src/components/NcAppNavigationCounter/NcAppNavigationCounter.vue
  src/components/NcAppNavigationCounter/index.js
  src/components/index.js
Labels: 4. to release, feature: app-navigation, breaking

#4099 target=_blank in NcSettingsSection.vue
  src/components/NcSettingsSection/NcSettingsSection.vue
Labels: bug, 4. to release, backport-request, feature: settings

#4103 Files : Left panel dropdown improvement for NC 26
  src/components/NcAppNavigationItem/NcAppNavigationIconCollapsible.vue
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review, feature: app-navigation, design

#4113 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#4112 NcAppSidebarTabs: fix rendering tabs with CSS icon in `OCA.Files.Sidebar`
  src/components/NcAppSidebar/NcAppSidebarTabs.vue
  src/components/NcAppSidebarTab/NcAppSidebarTab.vue
Labels: bug, 3. to review, feature: app-sidebar

#4118 Release v7.11.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#4110 Remove unused props and directives of NcResource
  src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
  src/components/NcRelatedResourcesPanel/NcResource.vue
Labels: 3. to review, feature: related resources panel

#4111 NcAppSidebar: fix tabs with css icon
  src/components/NcAppSidebar/NcAppSidebarTabs.vue
  src/components/NcAppSidebarTab/NcAppSidebarTab.vue
Labels: bug, 3. to review, feature: app-sidebar

#4121 fix(NcResource): Alignment
  src/components/NcRelatedResourcesPanel/NcResource.vue
Labels: bug, 3. to review, backport-request, feature: related resources panel

#4102 chore: Add pull_request_template.md to emphasize better PRs
  .github/pull_request_template.md
Labels: 3. to review, technical debt

#3894 Replace unmaintained HammerJS dependency with VueUse
  package-lock.json
  package.json
  src/components/NcAppContent/NcAppContent.vue
  src/components/NcModal/NcModal.vue
Labels: 4. to release, dependencies

#4109 Add aria-expanded to settings accordion button
  l10n/messages.pot
  src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue
Labels: accessibility

#4065 fix(NcCheckboxRadioSwitch): Align icon slot properly
  src/components/NcAppSidebar/NcAppSidebarTabs.vue
  src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
Labels: 3. to review, design, feature: checkbox-radio-switch

#4107 Input Fields and RichContenteditable: add focus and select methods
  src/components/NcInputField/NcInputField.vue
  src/components/NcPasswordField/NcPasswordField.vue
  src/components/NcRichContenteditable/NcRichContenteditable.vue
  src/components/NcTextField/NcTextField.vue
Labels: 3. to review, feature: rich-contenteditable, feature: input-field

#4129 Automated styling update from server
  styleguide/assets/default.css
  styleguide/assets/server.css
Labels: 4. to release, dependencies

#4063 Add info NoteCard
  src/components/NcNoteCard/NcNoteCard.vue
Labels: enhancement, 3. to review

#4135 Fix alignment of nav contents
  src/components/NcAppNavigation/NcAppNavigation.vue
Labels: bug, 3. to review, papercut, design

#3895 feat: Add slot for description of `NcEmptyContent`
  src/components/NcEmptyContent/NcEmptyContent.vue
Labels: enhancement, 3. to review, feature: emptycontent

#4134 fix toggle overlapping other stuff
  src/components/NcAppNavigationItem/NcAppNavigationIconCollapsible.vue
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review, regression, design, backport-request

#4152 collapse sections by default to make the styleguide a bit lucid
  styleguide.config.js
Labels: enhancement, 3. to review

#4154 fix visibility of default counterbubble
  src/components/NcCounterBubble/NcCounterBubble.vue
Labels: bug, 3. to review, accessibility

#4084 enh(NcActions): Navigation link actions
  src/components/NcActions/NcActions.vue
Labels: 4. to release, feature: actions, accessibility, backport-request

#4153 make navigation-collapsible always visible
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: 3. to review, backport-request

#4162 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#4166 Export dist a11y activation util
  src/functions/a11y/index.js
  src/functions/index.js
  src/index.js
Labels: 3. to review, accessibility, backport-request
