Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2023-04, with the labels that each got.

#3947 Add additionalTrapElements prop to settingsDialog
  src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue
Labels: enhancement, 3. to review

#3953 7.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3957 Add placeholder for heading inside of app content
  src/components/NcAppContent/NcAppContent.vue
Labels: 3. to review

#3954 Fix native open in a new tab in components with a custom router link
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
  src/components/NcListItem/NcListItem.vue
Labels: 3. to review

#3961 Adjust some smart picker strings
  l10n/messages.pot
  src/components/NcRichText/NcReferencePicker/NcProviderList.vue
  src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue
Labels: enhancement, 3. to review, feature: richtext

#3967 Remove unused tooltip directive
  src/components/NcActions/NcActions.vue
Labels: 3. to review, feature: actions

#3962 Remove the smart picker modal padding
  src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue
  src/components/NcRichText/NcReferencePicker/NcSearch.vue
Labels: enhancement, 3. to review, feature: richtext

#3955 Automated styling update from server
  styleguide/assets/server.css
Labels: 4. to release, dependencies

#3972 adjust sidebar to go full-screen earlier at 768px
  src/components/NcAppNavigation/NcAppNavigation.vue
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: enhancement, 3. to review

#3973 Don't overwrite router-link href in NcBreadcrumb
  src/components/NcBreadcrumb/NcBreadcrumb.vue
Labels: bug, 3. to review, feature: breadcrumbs

#3974 fix(NcHeaderMenu): fix unnecessary filter invert
  src/components/NcHeaderMenu/NcHeaderMenu.vue
Labels: bug, 3. to review, design

#3968 feat(NcSelectTags): Disable internal v-model and options handling
  src/components/NcSelectTags/NcSelectTags.vue
Labels: enhancement, 4. to release, feature: select

#3979 Split Bootstrap version reference in Tooltip .scss
  src/directives/Tooltip/index.scss
Labels: 3. to review, feature: tooltip

#3980 Fix inverted validate label check in NcInputField
  src/components/NcInputField/NcInputField.vue
Labels: bug, 3. to review, feature: input-field

#3981 v7.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release

#3986 Update CHANGELOG for 7.10.0
  CHANGELOG.md
Labels: 3. to review

#3984 feat(NcRichContenteditable): Allow to pass in an icon URL
  src/components/NcRichContenteditable/NcAutoCompleteResult.vue
Labels: enhancement, 3. to review, feature: rich-contenteditable

#3945 Improve `NcCheckboxRadioSwitch` and use for `NcAppSidebarTabs`
  src/components/NcAppSidebar/NcAppSidebar.vue
  src/components/NcAppSidebar/NcAppSidebarTabs.vue
  src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
  tests/unit/components/NcAppSidebar/NcAppSidebarTabs.spec.js
Labels: 3. to review, design, feature: app-sidebar, feature: checkbox-radio-switch

#3987 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#4003 Use NcSelect in NcAppSidebar example
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: 3. to review, feature: select

#3996 Disable wrap on overflow
  src/components/NcSelect/NcSelect.vue
Labels: bug, 4. to release, feature: select

#4004 NcAppSidebarTabs: fix activating the tab being added
  src/components/NcAppSidebar/NcAppSidebarTabs.vue
Labels: bug, 3. to review, feature: app-sidebar

#4005 Automated styling update from server
  styleguide/assets/icons.css
Labels: 3. to review, dependencies

#4007 feat(NcRichContenteditable): Support iconUrl on mention bubbles
  src/components/NcRichContenteditable/NcMentionBubble.vue
Labels: bug, 3. to review, feature: rich-contenteditable

#4010 Allow to override showTrailingButton from an NcAction
  src/components/NcActionInput/NcActionInput.vue
  src/components/NcPasswordField/NcPasswordField.vue
Labels: 2. developing, feature: actions, feature: input-field

#4015 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies
