Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2023-01, with the labels that each got.

#3608 fix(NcAppNavigationItem): Make sure that icon-collapse styles take precendense over NcButton styles
  src/components/NcAppNavigationItem/NcAppNavigationIconCollapsible.vue
Labels: bug, 3. to review

#3573 Add console warning messages for deprecated multiselect components
  .eslintrc.js
  src/components/NcMultiselect/NcMultiselect.vue
  src/components/NcMultiselectTags/NcMultiselectTags.vue
  tests/setup.js
  webpack.config.js
Labels: 4. to release, feature: select/multiselect

#3613 fix(ProgressBar): Fix progress rounded corners
  src/components/NcProgressBar/NcProgressBar.vue
Labels: bug, 4. to release

#3614 Fix action input styles
  src/components/NcActionInput/NcActionInput.vue
Labels: bug, 3. to review

#3612 feat(AppNavigationItem): Add href support
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: enhancement, 3. to review

#3618 Do not add aria-label when avatar is not interactive
  src/components/NcAvatar/NcAvatar.vue
Labels: bug, 3. to review, feature: avatar, accessibility

#3620 Simplify NcListItemIcon default slot usage
  src/components/NcListItemIcon/NcListItemIcon.vue
Labels: 3. to review, feature: list-item-icon

#3619 Use material design icons in documentation everywhere
  src/components/NcActionButton/NcActionButton.vue
  src/components/NcActionInput/NcActionInput.vue
  src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
  src/components/NcAppNavigationNewItem/NcAppNavigationNewItem.vue
  src/components/NcAppSidebar/NcAppSidebar.vue
  src/components/NcContent/NcContent.vue
  src/components/NcListItemIcon/NcListItemIcon.vue
Labels: 3. to review, feature: documentation, design

#3631 Automated styling update from server
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_true-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_false-compact_false-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_null-compact_false-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_null-starred_true-compact_false-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_false-compact_false-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_null-compact_false-header_none-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_image-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_image-secondary_none-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_none-secondary_button-editable_true-base.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subtitle_true-starred_true-compact_false-header_none-secondary_none-editable_true-base.png
  styleguide/assets/icons.css
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#3630 Add NcIconSvgWrapper to public API
  l10n/messages.pot
  src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue
  src/components/NcIconSvgWrapper/index.js
  src/components/NcListItemIcon/NcListItemIcon.vue
  src/components/index.js
Labels: enhancement, 3. to review, accessibility

#3575 Add `NcSavingIndicatorIcon`
  src/components/NcSavingIndicatorIcon/NcSavingIndicatorIcon.vue
  src/components/NcSavingIndicatorIcon/index.js
  src/components/index.js
Labels: enhancement, 3. to review

#3632 Fix minor typo in NcContent docs
  src/components/NcContent/NcContent.vue
Labels: 3. to review, feature: app-content

#3637 Adjust border thickness of NcRichContenteditable
  src/components/NcRichContenteditable/NcRichContenteditable.vue
Labels: 3. to review, design

#3638 Bump vue-select to 3.20.2
  package-lock.json
  package.json
Labels: bug, 3. to review, feature: select/multiselect, dependencies

#3617 feat(AppNavigationItem): Allow native title attribute control
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: 3. to review, accessibility

#3455 add compile command for l10n
  .github/workflows/command-l10n-update.yml
Labels: 3. to review

#3640 Fix lint errors
  src/components/NcActions/NcActions.vue
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
  src/components/NcBreadcrumb/NcBreadcrumb.vue
  src/components/NcBreadcrumbs/NcBreadcrumbs.vue
  src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
  src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
  src/components/NcHighlight/NcHighlight.vue
  src/components/NcTimezonePicker/timezoneDataProviderService.js
  src/components/NcVNodes/NcVNodes.vue
  src/utils/GetParent.js
Labels: 3. to review

#3643 7.4.0-beta.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3644 Revert webpack output file name
  webpack.config.js
Labels: bug, 4. to release

#3645 7.4.0-beta.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3648 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#3649 7.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#3654 Breadcrumb: add exact prop and fix style
  src/components/NcBreadcrumb/NcBreadcrumb.vue
Labels: bug, enhancement, 3. to review, feature: breadcrumbs

#3653 Breadcrumb: add exact prop and fix style
  src/components/NcBreadcrumb/NcBreadcrumb.vue
Labels: bug, enhancement, 3. to review, feature: breadcrumbs

#3656 Set placement of select dropdown
  package-lock.json
  package.json
  src/components/NcSelect/NcSelect.vue
Labels: enhancement, 4. to release, feature: select/multiselect, accessibility

#3665 Fix invalid svg errors in styleguide
  webpack.config.js
Labels: bug, 3. to review, regression

#3663 v7.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release

#3571 Add `NcActionButtonGroup` to inline `NcActionButton`s within the action menu
  src/components/NcActionButtonGroup/NcActionButtonGroup.vue
  src/components/NcActionButtonGroup/index.js
  src/components/index.js
Labels: enhancement, 3. to review, feature: actions

#3680 Add aria-labels to colorpicker buttons
  l10n/messages.pot
  src/components/NcColorPicker/NcColorPicker.vue
Labels: bug, 3. to review, accessibility, feature: colorpicker

#3686 chore(l10n): update l10n readme
  README.md
Labels: 3. to review

#3697 Fix: update transition styles for NcButton
  src/components/NcButton/NcButton.vue
Labels: bug, 3. to review, feature: button

#3700 Small cleanup of the NcActions docs
  src/components/NcActions/NcActions.vue
Labels: 3. to review, feature: actions, papercut

#3702 Update `@nextcloud/eslint-config` to 8.2.1
  package-lock.json
  package.json
Labels: 3. to review, dependencies
