Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2024-06, with the labels that each got.

#5658 Automated styling update from server
  styleguide/assets/default.css
Labels: 3. to review, dependencies

#5666 fix: re-export `NcEllipsisedOption` and `NcInputField` in root export
  src/components/index.js
Labels: bug, 3. to review, backport-request, feature: input-field, feature: ellipsised-option

#5664 fix(NcVNodes): add re-export in root export and add docs
  src/components/NcVNodes/NcVNodes.vue
  src/components/index.js
Labels: bug, 3. to review, feature: documentation, backport-request

#5663 chore(NcEllipsisedOption): add docs
  src/components/NcEllipsisedOption/NcEllipsisedOption.vue
Labels: feature: documentation, feature: select, backport-request, feature: ellipsised-option

#5672 [next] fix(NcRichText): crash on router links rendering
  package-lock.json
  package.json
  src/components/NcRichText/NcRichText.vue
Labels: bug, 3. to review, feature: richtext

#5661 chore: replace @nextcloud/calendar-js with @nextcloud/timezones
  .github/workflows/update_timezones.yml
  package-lock.json
  package.json
  resources/timezones/README.md
  resources/timezones/update-zones.py
  resources/timezones/zones.json
  src/components/NcTimezonePicker/timezoneDataProviderService.js
  webpack.config.js
Labels: 3. to review, dependencies, backport-request

#5677 [next] chore: replace @nextcloud/calendar-js with @nextcloud/timezones
  .github/workflows/update_timezones.yml
  package-lock.json
  package.json
  resources/timezones/README.md
  resources/timezones/update-zones.py
  resources/timezones/zones.json
  src/components/NcTimezonePicker/timezoneDataProviderService.js
  webpack.config.cjs
Labels: 3. to review, dependencies

#5668 [next] fix: re-export `NcEllipsisedOption` and `NcInputField` in root export
  src/components/index.ts
Labels: bug, 3. to review, feature: input-field, feature: ellipsised-option

#5679 feat(NcDialogButton): Allow to pass `disabled` prop
  src/components/NcDialogButton/NcDialogButton.vue
Labels: enhancement, 3. to review, feature: dialog, backport-request

#5678 Automated styling update from server
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-entry-menu-active.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-entry.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-route-menu-active.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-route.png
  styleguide/assets/icons.css
Labels: 3. to review, dependencies

#5674 feat(NcRichContenteditable): programmatically show tributes
  src/components/NcRichContenteditable/NcRichContenteditable.vue
Labels: enhancement, 3. to review, feature: rich-contenteditable

#5686 feat: Add NcChip component
  package-lock.json
  package.json
  src/components/NcButton/NcButton.vue
  src/components/NcChip/NcChip.vue
  src/components/NcChip/index.js
  src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue
  styleguide/global.requires.js
Labels: enhancement, 3. to review

#5669 chore(functions): add docs
  docs/functions.md
  docs/functions/a11y.md
  docs/functions/emoji.md
  docs/functions/reference.md
  docs/functions/registerReference.md
  docs/functions/usernameToColor.md
  src/functions/emoji/emoji.ts
  src/functions/usernameToColor/usernameToColor.js
  styleguide.config.js
  styleguide/global.requires.js
Labels: 3. to review, feature: documentation, feature: functions

#5695 feat(NcAppSidebar): add `toggleAttrs` prop to pass attributes on the toggle button
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: enhancement, 3. to review, feature: app-sidebar

#5703 fix(richText): do not handle relative links without leading slash as router links
  src/components/NcRichText/autolink.js
  tests/unit/components/NcRichText/autoLink.spec.js
Labels: bug, 3. to review, feature: avatar, feature: richtext

#5702 feat(NcAppSidebar): add noToggle prop to hide the built-in toggle button
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: enhancement, 3. to review, feature: app-sidebar

#5656 fix(NcModal): Adjust modal header name and actions
  src/components/NcModal/NcModal.vue
  styleguide/assets/additional.css
  styleguide/assets/dark.css
Labels: bug, 3. to review, backport-request

#5709 fix(REUSE): add SPDX header to a new file
  styleguide/assets/dark.css
  styleguide/assets/default.css
Labels: 3. to review, technical debt

#5665 chore(directives): add docs
  docs/directives.md
  docs/directives/focus.md
  docs/directives/linkify.md
  docs/directives/tooltip.md
  styleguide.config.js
  styleguide/global.requires.js
Labels: 3. to review, feature: documentation

#5720 fix(NcAppSidebar): apply toggle offset transition only on sidebar transition
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: bug, 3. to review, feature: app-sidebar

#5715 chore(NcUserStatusIcon): remove warn if status is not set
  src/components/NcUserStatusIcon/NcUserStatusIcon.vue
Labels: 3. to review, technical debt

#5728 fix: japanese system tags translation
  l10n/ja.pot
Labels: bug, 3. to review, backport-request

#5724 chore: Prepare v8.13.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#5736 chore: Update dependencies on `next` branch
  .eslintrc.json
  cypress.config.ts
  package-lock.json
  package.json
Labels: 3. to review, dependencies, vue 3

#5738 chore: Prepare 9.0.0-alpha.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, vue 3

#5740 feat(NcAppSidebar): force show navigation for a single tab
  src/components/NcAppSidebar/NcAppSidebar.vue
  src/components/NcAppSidebar/NcAppSidebarTabs.vue
Labels: enhancement, 3. to review, feature: app-sidebar

#5742 Automated styling update from server
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-entry-menu-active.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-entry.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-route-menu-active.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-route.png
  styleguide/assets/server.css
Labels: 3. to review, dependencies
