Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2024-07, with the labels that each got.

#5749 fix(NcRichContentEditable): remove overlapping placeholder with tribute trigger
  src/components/NcRichContenteditable/NcRichContenteditable.vue
Labels: 3. to review, regression, feature: rich-contenteditable

#5744 [next] chore(NcUserStatusIcon): remove warn if status is not set
  src/components/NcUserStatusIcon/NcUserStatusIcon.vue
Labels: 3. to review, technical debt

#5753 fix(NcMentionBubble): hide selectable mention id from widescreens
  src/components/NcRichContenteditable/NcMentionBubble.vue
Labels: bug, 3. to review, feature: rich-contenteditable

#5754 fix(NcReferenceWidget): pass elements to intersection observer
  src/components/NcRichText/NcReferenceWidget.vue
Labels: 3. to review, regression, backport-request

#5747 style(NcHeaderMenu): pass text-on-background color for header menu
  src/components/NcHeaderMenu/NcHeaderMenu.vue
Labels: bug, 3. to review, backport-request, feature: header-menu

#5761 Automated styling update from server
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-entry-menu-active.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-entry.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-route-menu-active.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-route.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-tertiary-non-active-entry.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-tertiary-non-active-route.png
  styleguide/assets/icons.css
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#5767 feat(NcButton): Add `size` prop to allow setting the button size to `small`, `normal`, `large`
  src/components/NcButton/NcButton.vue
  src/components/NcHeaderMenu/NcHeaderMenu.vue
Labels: enhancement, 3. to review, backport-request, feature: button

#5757 feat: migrate `NcCollectionList` component from `nextcloud-vue-collections`
  l10n/messages.pot
  src/components/NcCollectionList/NcCollectionList.vue
  src/components/NcCollectionList/NcCollectionListItem.vue
  src/components/NcCollectionList/index.js
  src/components/NcCollectionList/service.ts
  src/components/NcCollectionList/useCollections.js
  src/components/index.js
  styleguide.config.js
Labels: enhancement, 4. to release, component, backport-request

#5771 fix(NcDialog): Ensure the dialog is correctly labelled by its name
  cypress/component/NcAppSettingsDialog.cy.ts
  cypress/component/NcDialog.cy.ts
  cypress/component/NcModal.cy.ts
  cypress/component/modal.cy.ts
  cypress/support/commands.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  src/components/NcAppSettingsSection/NcAppSettingsSection.vue
  src/components/NcDialog/NcDialog.vue
  src/components/NcModal/NcModal.vue
Labels: bug, enhancement, 3. to review, feature: dialog, backport-request

#5773 Automated styling update from server
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-entry-menu-active.png
  cypress/snapshots/base/AppNavigationItem.cy.ts/NcAppNavigationItem-primary-on-active-route-menu-active.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_false-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_none-secondary_none-editable_true.png
  src/composables/actions/useActionText.ts
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#5777 fix(NcCheckboxRadioSwitch): only bind aria attributes to the input
  .reuse/dep5
  cypress/commands.d.ts
  cypress/component/NcCheckboxRadioSwitch.cy.ts
  cypress/support/commands.ts
  cypress/support/component.ts
  src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
  tests/unit/components/NcCheckboxRadioSwitch/checkbox.spec.js
Labels: bug, 4. to release, regression, feature: checkbox-radio-switch, Developer experience

#5779 chore: Prepare release of 8.14.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#5791 Migrate REUSE to TOML
  .github/workflows/reuse.yml
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, backport-request, technical debt

#5792 Migrate REUSE to TOML
  .github/workflows/reuse.yml
  .reuse/dep5
  REUSE.toml
Labels: 4. to release

#5793 Use correct date in header
  REUSE.toml
Labels: bug, 4. to release

#5794 Add reuse status badge
  README.md
Labels: feature: documentation

#5786 Automated styling update from server
  styleguide/assets/default.css
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#5765 fix(NcAppNavigationSettings): border radius of toggle button
  src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue
Labels: bug, 3. to review, feature: app-navigation, design, backport-request

#5568 [next] fix(NcAppNavigationCaption): Only pass needed props to NcActions
  src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
  tests/unit/components/NcAppNavigation/NcAppNavigationCaption.spec.ts
Labels: bug, feature: app-navigation, vue 3

#5804 fix(NcAppNavigationCaption ): properly align with NcAppNavigationItem
  src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
Labels: bug, 4. to release, feature: app-navigation, backport-request

#5806 fix(NcActions): Use full window height
  src/components/NcActions/NcActions.vue
  styleguide.config.js
  styleguide/assets/styleguide.css
Labels: bug, 3. to review, feature: actions

#5810 chore(docs): remove SPDX header from component docs
  src/mixins/actionGlobal.js
  src/mixins/clickOutsideOptions/index.js
Labels: 3. to review, feature: documentation

#5814 fix(NcAppNavigationSettings): use tertiary styling for the toggle button
  src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue
Labels: 3. to review, feature: app-navigation, design, backport-request

#5815 style(NcAppNavigationCaption): remove margin-bottom
  src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
Labels: 3. to review

#5820 docs: Fix `NcAppNavigationCaption` examples
  src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
Labels: bug, 3. to review, feature: documentation, backport-request

#5822 fix(NcInputField): Make helper text aligned and maxcontrast color
  src/components/NcInputField/NcInputField.vue
  src/components/NcTextField/NcTextField.vue
Labels: bug, 3. to review, design, backport-request, feature: input-field

#5821 fix(NcInputField): Make sure label and placeholder is not jumping
  src/components/NcInputField/NcInputField.vue
Labels: bug, 3. to review, backport-request, feature: input-field

#5780 fix(NcListItem): Anchor height was set not to content but random area
  src/components/NcListItem/NcListItem.vue
Labels: bug, 3. to review, feature: list-item

#5834 fix(NcListItem): do not render counter on falsy values
  src/components/NcListItem/NcListItem.vue
Labels: bug, 3. to review, backport-request, feature: list-item

#5819 NcAppSettingsSection: make titles normal h3 size
  src/components/NcAppSettingsSection/NcAppSettingsSection.vue
Labels: 3. to review, backport-request

#5833 fix(NcAppSidebar): manage focus only after transition has finished
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: bug, 3. to review, feature: app-sidebar

#5842 fix(NcActions): assign NcContent as NcActions > NcPopover default boundaries
  src/components/NcActions/NcActions.vue
Labels: 3. to review, feature: actions, regression

#5816 fix(NcColorPicker): Make the color circle size depend on clickable area
  src/components/NcColorPicker/NcColorPicker.vue
Labels: bug, 4. to release, regression, backport-request, feature: colorpicker

#5843 fix(NcAppContent): splitpane splitter styles with dark theme
  src/components/NcAppContent/NcAppContent.vue
Labels: bug, 3. to review, feature: app-content-list

#5831 feat(NcAppNavigation): Provide consistent in-app search
  l10n/messages.pot
  src/components/NcAppNavigation/NcAppNavigation.vue
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
  src/components/NcAppNavigationNewItem/NcAppNavigationNewItem.vue
  src/components/NcAppNavigationSearch/NcAppNavigationSearch.vue
  src/components/NcAppNavigationSearch/index.js
  src/components/index.js
Labels: enhancement, 3. to review, feature: app-navigation, backport-request

#5850 fix(NcAppNavigationSearch): Fix focus button when clearing search
  src/components/NcAppNavigationSearch/NcAppNavigationSearch.vue
Labels: bug, 3. to review

#5844 chore: prepare release 8.15.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#5853 fix: alignement of listitem name for one line layout
  src/components/NcListItem/NcListItem.vue
Labels: bug, 3. to review, backport-request

#5830 NcListItem: remove max width
  src/components/NcListItem/NcListItem.vue
Labels: 3. to review

#5857 fix(NcAppNavigation): update docs example with NcAppNavigationSearch component
  src/components/NcAppNavigation/NcAppNavigation.vue
Labels: 3. to review, feature: app-navigation, technical debt

#5839 NcActionCheckbox: align with NcActionText
  src/components/NcActionCheckbox/NcActionCheckbox.vue
Labels: 3. to review

#5829 NcSelect: make same height and color as NcTextField
  src/components/NcInputField/NcInputField.vue
  src/components/NcSelect/NcSelect.vue
Labels: 3. to review

#5865 fix(NcSelect): increase avatar size to show subname
  src/components/NcSelect/NcSelect.vue
Labels: bug, 3. to review, feature: select

#5801 Automated styling update from server
  REUSE.toml
  styleguide/assets/dark.css
  styleguide/assets/default.css
  styleguide/assets/icons.css
  styleguide/assets/img/app-background.jpg
  styleguide/assets/img/background/jenna-kim-the-globe-dark.webp
  styleguide/assets/img/background/jenna-kim-the-globe.webp
  styleguide/assets/img/background/kamil-porembinski-clouds.jpg
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#5877 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#5859 fix(NcChip): Ensure chips without icon do not reserve empty space for icon
  src/components/NcChip/NcChip.vue
Labels: bug, 3. to review, design, backport-request

#5879 fix(NcListItem): Make paddings smaller again on Nextcloud 30
  src/components/NcListItem/NcListItem.vue
Labels: bug, 3. to review

#5881 chore: Prepare v8.15.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
