Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2024-10, with the labels that each got.

#6110 [next] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6111 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#6108 [NcRichText] Add style to mount point for custom picker and custom widget elements
  src/components/NcRichText/NcReferencePicker/NcReferencePicker.vue
  src/components/NcRichText/NcReferenceWidget.vue
Labels: enhancement, 3. to review, technical debt, feature: richtext

#6139 Automated styling update from server
  styleguide/assets/icons.css
Labels: 3. to review, dependencies

#6137 fix(reference-picker): allow closing modal dialog on NcReferencePicker
  src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue
Labels: bug, 3. to review, feature: smart picker

#6151 feat(NcRichText): make interactive widgets opt-in
  src/components/NcRichText/NcReferenceList.vue
  src/components/NcRichText/NcReferenceWidget.vue
  src/components/NcRichText/NcRichText.vue
Labels: enhancement, 3. to review, backport-request, feature: richtext

#6148 fix(NcActions): RTL support
  src/assets/action.scss
Labels: bug, 3. to review, feature: actions, backport-request

#6144 fix(NcAppNavigation): RTL support
  src/components/NcAppNavigation/NcAppNavigation.vue
  src/components/NcAppNavigationToggle/NcAppNavigationToggle.vue
Labels: bug, 3. to review, feature: app-navigation, backport-request

#6142 [next] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6154 [next] fix(NcAppSidebar): apply toggle offset transition only on sidebar transition
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: bug, 3. to review, feature: app-sidebar

#6145 fix(NcAppDetailsToggle): Rtl support
  src/components/NcAppContent/NcAppDetailsToggle.vue
Labels: bug, 3. to review, backport-request

#6095 fix(NcDateTimePicker): change styling to look more like the native picker
  src/components/NcDateTimePicker/NcDateTimePicker.vue
  src/components/NcDateTimePicker/index.scss
Labels: bug, 3. to review, feature: datepicker, design

#6168 [next] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5418 feat: add v-model support for input-like components
  src/components/NcActionCheckbox/NcActionCheckbox.vue
  src/components/NcActionInput/NcActionInput.vue
  src/components/NcActionRadio/NcActionRadio.vue
  src/components/NcActionTextEditable/NcActionTextEditable.vue
  src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
  src/components/NcInputField/NcInputField.vue
  src/components/NcPasswordField/NcPasswordField.vue
  src/components/NcRichContenteditable/NcRichContenteditable.vue
  src/components/NcSettingsInputText/NcSettingsInputText.vue
  src/components/NcTextArea/NcTextArea.vue
  src/components/NcTextField/NcTextField.vue
Labels: enhancement, 3. to review, feature: checkbox-radio-switch

#6161 fix(NcAppNavigationItem): use $scopedSlots instead of $slots
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
Labels: bug, 3. to review, feature: app-navigation, backport-request

#6171 fix(NcModal): rtl support
  src/components/NcModal/NcModal.vue
Labels: bug, 3. to review, design
