Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2024-05, with the labels that each got.

#5518 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#5554 fix(emoji): index emoji data once for search functions
  src/functions/emoji/emoji.ts
Labels: bug, 3. to review, feature: emoji picker

#5545 Automated styling update from server
  styleguide/assets/icons.css
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#5560 release: v8.11.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release

#5561 fix(NcReferenceWidget): use requestAnimationFrame in observers
  src/components/NcRichText/NcReferenceWidget.vue
Labels: bug, 3. to review

#5564 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#5572 fix: update timezone data and automate future updates
  .github/workflows/update_timezones.yml
  resources/timezones/update-zones.py
  resources/timezones/zones.json
Labels: 3. to review, backport-request, technical debt

#5567 feat(NcAppNavigationCaption): Allow to set heading level
  src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
  tests/unit/components/NcAppNavigation/NcAppNavigationCaption.spec.ts
Labels: enhancement, 3. to review, feature: app-navigation, backport-request

#5576 fix(NcAppNavigationCaption): Fix margin
  src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
Labels: bug, 3. to review, feature: app-navigation, backport-request

#5565 feat(NcAppNavigationCaption): Add `heading-id` prop to allow setting the ID on the caption itself
  src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
  tests/unit/components/NcAppNavigation/NcAppNavigation.spec.js
  tests/unit/components/NcAppNavigation/NcAppNavigationCaption.spec.ts
Labels: enhancement, 3. to review, feature: app-navigation

#5580 [next] feat(NcAppNavigationCaption): Add `heading-id` prop
  src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
  tests/unit/components/NcAppNavigation/NcAppNavigation.spec.js
  tests/unit/components/NcAppNavigation/NcAppNavigationCaption.spec.ts
Labels: enhancement, 3. to review, vue 3

#5569 [next] fix: Adjust tsconfig and eslintrc for tests
  cypress/.eslintrc.json
  cypress/tsconfig.json
  package-lock.json
  package.json
  tests/.eslintrc.js
  tsconfig.json
Labels: bug, 3. to review, vue 3

#5266 [next] chore: Update and pin development dependencies
  package-lock.json
  package.json
  webpack.config.cjs
Labels: 3. to review, vue 3

#5587 fix(NcReferenceWidget): useElementSize
  src/components/NcRichText/NcReferenceWidget.vue
Labels: bug, 3. to review, backport-request

#5583 fix: Adjust Typescript definition export
  cypress/tsconfig.json
  package.json
  src/components/NcButton/NcButton.vue
  tests/tsconfig.json
  tsconfig.json
  vite.config.ts
Labels: bug, 3. to review, vue 3

#5581 fix(docs): Add missing file extensions to vue-material-design-icons imports
  src/components/NcActionButton/NcActionButton.vue
  src/components/NcActionLink/NcActionLink.vue
  src/components/NcActions/NcActions.vue
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
  src/components/NcAppSidebar/NcAppSidebar.vue
  src/components/NcAvatar/NcAvatar.vue
  src/components/NcButton/NcButton.vue
  src/components/NcEmptyContent/NcEmptyContent.vue
  src/components/NcListItemIcon/NcListItemIcon.vue
Labels: bug, 3. to review, feature: documentation, backport-request

#5514 Update NcSettingSection design
  src/components/NcSettingsSection/NcSettingsSection.vue
Labels: enhancement, 3. to review, breaking

#5584 feat(NcAppSidebar): Allow to set `open` state to prevent focus trap issues on mobile
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_true-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_true-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_true-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_true-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_false-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_none-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_image-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_image-secondary_none-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_none-secondary_button-editable_true.png
  cypress/snapshots/base/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_none-secondary_none-editable_true.png
  l10n/messages.pot
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: bug, 3. to review, feature: app-sidebar

#5603 feat(mobile): restore hiding the appnavigation on mobile
  src/components/NcAppNavigation/NcAppNavigation.vue
Labels: bug, 3. to review, regression, design

#5604 fix: Revert #5514 and only force width limit on Nextcloud 30+
  src/components/NcSettingsSection/NcSettingsSection.vue
Labels: bug, 3. to review, regression

#5606 [next] feat(NcAppSidebar): Allow to set open state to prevent focus trap issues on mobile #5584
  l10n/messages.pot
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: enhancement, 3. to review, breaking, vue 3

#5590 release: v8.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#5610 [next] refactor!: Drop CJS entry points, only provide ESM
  package.json
  vite.config.ts
Labels: bug, 3. to review, breaking, vue 3

#5613 fix(NcAppSidebar): remove hidden navigation toggle from focus trap
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: bug, 3. to review, regression, feature: app-sidebar, accessibility

#5617 [next] fix: Update styles from server
  styleguide/assets/icons.css
  styleguide/assets/server.css
Labels: 3. to review

#5483 Reduce border radius of components
  src/assets/NcAppNavigationItem.scss
  src/components/NcButton/NcButton.vue
  src/components/NcListItem/NcListItem.vue
Labels: 3. to review, design

#5639 Update temporary border radius variable
  src/assets/NcAppNavigationItem.scss
  src/components/NcButton/NcButton.vue
  src/components/NcListItem/NcListItem.vue
Labels: bug, 3. to review

#5629 Automated styling update from server
  styleguide/assets/default.css
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#5612 fix: Adjust license in `package.json`
  package-lock.json
  package.json
Labels: bug, 3. to review, backport-request

#5611 chore: Prepare v9.0.0-alpha.3 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, vue 3

#5645 refactor: Drop unused files from source
  build/usernameToColor-export.js
  src/utils/IsOutOfViewport.js
Labels: 3. to review

#5644 [next] fix: Adjust license in package.json
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#5646 refactor: Fix linter issues on test case files
  tests/.eslintrc.js
  tests/unit/components/NcHighlight/NcHighlight.spec.js
  tests/unit/components/NcRichText/NcRichText.spec.js
  tests/unit/utils/FindRanges.spec.js
Labels: 3. to review

#5647 chore: Update CI workflow files from template
  .github/workflows/command-l10n-update.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/l10n.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-publish.yml
  .github/workflows/server-styling-update.yml
  .github/workflows/transifex-approve-merge.yml
  .github/workflows/update_timezones.yml
Labels: 3. to review

#5563 Use variables for input border width
  src/components/NcInputField/NcInputField.vue
  src/components/NcSelect/NcSelect.vue
  src/components/NcTextArea/NcTextArea.vue
Labels: bug, 3. to review
