Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2025-04, with the labels that each got.

#5440 add fallBackFocus to NcPopover
  src/components/NcPopover/NcPopover.vue
Labels: bug, 3. to review

#6669 fix(NcAvatar): keep line-height only for 'initials' avatars
  src/components/NcAvatar/NcAvatar.vue
Labels: bug, 3. to review, feature: avatar, backport-request

#6681 [next] refactor: consistent export style for `isSlotPopulated`
  src/components/NcActions/NcActions.vue
  src/components/NcAppSidebar/NcAppSidebar.vue
  src/components/NcBreadcrumbs/NcBreadcrumbs.vue
  src/components/NcButton/NcButton.vue
  src/utils/isSlotPopulated.ts
  tests/unit/utils/isSlotPopulated.spec.ts
Labels: 3. to review, vue 3, refactor ♻️

#6683 feat(NcActions): fix listening to wrong event names and add `opened` event / [NcPopover] animation wait
  src/components/NcActionButton/NcActionButton.vue
  src/components/NcActions/NcActions.vue
  src/components/NcAppNavigationNew/NcAppNavigationNew.vue
  src/components/NcAvatar/NcAvatar.vue
  src/components/NcPopover/NcPopover.vue
Labels: enhancement, 3. to review, feature: actions, backport-request

#6686 [next] chore: sync translations from master
  l10n/el.pot
  l10n/et_EE.pot
  l10n/is.pot
  l10n/pt_BR.pot
  l10n/pt_PT.pot
  l10n/sk.pot
  l10n/uz.pot
Labels: 3. to review, l10n, vue 3

#6687 fix(NcPopover): use `transitionend` to wait for popover show/hide animation end
  src/components/NcPopover/NcPopover.vue
Labels: 3. to review, feature: popover, feature: actions, backport-request

#6665 release: v8.24.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#6688 [next] fix(NcPopover): add `passive: true` to `transitionend` event listener
  src/components/NcPopover/NcPopover.vue
Labels: 3. to review, feature: popover, technical debt

#6697 chore: default branch is `main` and Vue 2 branch is `stable8`
  .github/dependabot.yml
  .github/pull_request_template.md
  README.md
  docs/index.md
  styleguide.config.cjs
Labels: 3. to review

#6701 chore: remove unused `GetChildren` util
  src/utils/GetChildren.js
Labels: 3. to review

#6702 chore: migrate `GetParent` to Typescript
  src/mixins/actionText.js
  src/utils/getParent.ts
  tests/unit/utils/getParent.spec.ts
Labels: 3. to review, refactor ♻️

#6706 fix(NcActions): trigger forgotten closed event and correctly handle open
  src/components/NcActions/NcActions.vue
Labels: bug, 3. to review, feature: actions, regression

#6707 Automated styling update from server
  styleguide/assets/apps.css
  styleguide/assets/default.css
  styleguide/assets/icons.css
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#6705 refactor(NcActions): use provide/inject instead of $parent search
  src/components/NcActionButton/NcActionButton.vue
  src/components/NcActionButtonGroup/NcActionButtonGroup.vue
  src/components/NcActionCaption/NcActionCaption.vue
  src/components/NcActionCheckbox/NcActionCheckbox.vue
  src/components/NcActionLink/NcActionLink.vue
  src/components/NcActionRadio/NcActionRadio.vue
  src/components/NcActionRouter/NcActionRouter.vue
  src/components/NcActionText/NcActionText.vue
  src/components/NcActions/NcActions.vue
  src/components/NcActions/useNcActions.ts
  src/mixins/actionText.js
  src/utils/getParent.ts
  tests/unit/utils/getParent.spec.ts
Labels: 3. to review, feature: actions, refactor ♻️

#6704 docs: improve examples and documentation for `NcDateTimePicker`
  src/components/NcDateTimePicker/NcDateTimePicker.vue
Labels: 3. to review, feature: documentation, vue 3

#6703 refactor: migrate linkify util and directive to Typescript
  package-lock.json
  package.json
  src/components/NcAppSidebar/NcAppSidebar.vue
  src/directives/Linkify/index.js
  src/directives/Linkify/index.ts
  src/directives/index.ts
  src/utils/Linkify.js
  src/utils/linkify.ts
  tests/unit/utils/linkify.spec.ts
Labels: 3. to review, refactor ♻️

#6712 chore: prepare release of v9.0.0-alpha.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#6722 fix(NcDateTimePicker): adjust padding to prevent horizontal scrolling
  src/components/NcDateTimePicker/NcDateTimePicker.vue
Labels: bug, 3. to review, design

#6723 fix(NcDateTimePicker): localize the default formatting
  src/components/NcDateTimePicker/NcDateTimePicker.vue
  tests/component/components/NcDateTimePicker.spec.ts
Labels: bug, 3. to review, feature: datepicker, l10n

#6729 fix(dialogs/spawnDialog): dialog cannot be closed
  src/functions/dialog/index.ts
Labels: bug, 3. to review, feature: functions

#6726 fix(NcDateTimePicker): prevent emitting `[Date, null]`
  src/components/NcDateTimePicker/NcDateTimePicker.vue
Labels: bug, 3. to review, feature: datepicker

#6727 docs(NcDateTimePicker): add prop documentation for all props
  src/components/NcDateTimePicker/NcDateTimePicker.vue
Labels: 3. to review, technical debt, refactor ♻️

#6735 chore: drop remaining cypress files
  cypress.config.ts
Labels: 3. to review

#6728 feat(NcDateTimePicker): add time range picker and align naming
  CHANGELOG.md
  src/components/NcDateTimePicker/NcDateTimePicker.vue
  tests/component/components/NcDateTimePicker.spec.ts
Labels: enhancement, 3. to review, feature: datepicker

#6725 chore: adjust package engines versions
  .github/workflows/command-l10n-update.yml
  .github/workflows/command-playwright-update.yml
  .github/workflows/l10n.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/npm-publish.yml
  .github/workflows/playwright.yml
  package-lock.json
  package.json
Labels: 3. to review

#6752 fix(dialogs/spawnDialog)!: support vue-devtool but loose appContext
  docs/functions/spawnDialog.md
  src/functions/dialog/index.ts
Labels: bug, 3. to review, 💥 breaking, feature: functions

#6738 [stable8] feat(NcDateTimePicker): add new types as alternative for `range` property
  CHANGELOG.md
  src/components/NcDateTimePicker/NcDateTimePicker.vue
Labels: enhancement, 3. to review, feature: datepicker

#6760 feat(dialogs/spawnDialogs)!: do not toRaw the result
  src/functions/dialog/index.ts
Labels: enhancement, 3. to review, 💥 breaking, feature: functions

#6761 refactor: deprecate `Tooltip` directive for accessibility
  CHANGELOG.md
  src/components/NcAppContent/NcAppDetailsToggle.vue
  src/components/NcModal/NcModal.vue
  src/components/NcRichContenteditable/NcRichContenteditable.vue
  src/directives/Tooltip/index.js
Labels: 3. to review, feature: tooltip, backport-request, refactor ♻️

#6733 Adjust all styles for RTL support and add `directional` prop to NcIconSvgWrapper
  src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue
  src/components/NcModal/NcModal.vue
  src/components/NcPopover/NcPopover.vue
  src/directives/Tooltip/index.scss
  stylelint.config.cjs
Labels: enhancement, 3. to review, backport-request, RTL

#6758 feat(dialogs/spawnDialog): return promise with the result
  docs/functions/spawnDialog.md
  src/functions/dialog/index.ts
Labels: enhancement, 3. to review, feature: functions

#6759 feat(dialogs/spawnDialog)!: replace onClose callback with Promise
  docs/functions/spawnDialog.md
  src/functions/dialog/index.ts
Labels: enhancement, 3. to review, 💥 breaking, feature: functions

#6719 refactor!(NcModal): adjust to boolean props with default `false`
  CHANGELOG.md
  src/components/NcModal/NcModal.vue
  tests/component/components/NcModal.spec.ts
Labels: 3. to review, backport-request, 💥 breaking, refactor ♻️

#6779 refactor: drop `string-length` dependency and replace with native solution
  package-lock.json
  package.json
  src/components/NcRichContenteditable/NcRichContenteditable.vue
Labels: 3. to review, refactor ♻️

#6781 fix(dialogs/spawnDialog): enhance `spawnDialog` types
  src/functions/dialog/index.ts
Labels: bug, 3. to review, feature: functions

#6778 fix(NcRichContenteditable): add correct tooltip
  l10n/messages.pot
  src/components/NcRichContenteditable/NcRichContenteditable.vue
Labels: bug, 3. to review, regression

#6737 chore: type check project on CI
  .github/workflows/lint-typescript.yml
  package-lock.json
  package.json
  src/components/NcButton/NcButton.vue
  src/components/NcDateTimePicker/NcDateTimePicker.vue
  src/components/NcDialog/NcDialog.vue
  tsconfig.json
Labels: 3. to review, technical debt, refactor ♻️

#6734 refactor: adjust code to fix all SASS deprecations
  src/assets/NcAppNavigationItem.scss
  src/assets/action.scss
  src/assets/inputs.scss
  src/components/NcActionButton/NcActionButton.vue
  src/components/NcActionCheckbox/NcActionCheckbox.vue
  src/components/NcActionInput/NcActionInput.vue
  src/components/NcActionLink/NcActionLink.vue
  src/components/NcActionRadio/NcActionRadio.vue
  src/components/NcActionRouter/NcActionRouter.vue
  src/components/NcActionText/NcActionText.vue
  src/components/NcActionTextEditable/NcActionTextEditable.vue
  src/components/NcAppNavigationItem/NcAppNavigationItem.vue
  src/components/NcAppNavigationNewItem/NcAppNavigationNewItem.vue
  src/components/NcButton/NcButton.vue
  src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue
  src/components/NcCheckboxRadioSwitch/NcCheckboxRadioSwitch.vue
  src/components/NcHeaderButton/NcHeaderButton.vue
  src/components/NcHeaderMenu/NcHeaderMenu.vue
  src/components/NcHeaderMenu/header-menu__trigger.scss
  src/components/NcRichText/NcRichText.vue
  src/components/NcRichText/richtext.scss
  webpack.config.cjs
Labels: 3. to review, technical debt, refactor ♻️

#6033 refactor: Migrate `NcButton` from render function to template
  package.json
  src/components/NcButton/NcButton.vue
  src/components/NcButton/index.ts
  src/components/NcButton/types.ts
  src/components/NcDialogButton/NcDialogButton.vue
  src/globals.d.ts
  tests/component/components/NcButton.spec.ts
  tests/global-setup.js
  tests/unit/components/NcDialogButton/NcDialogButton.spec.ts
  tsconfig.json
  vitest.config.ts
Labels: 3. to review, feature: button, vue 3, refactor ♻️

#6785 fix(NcRichContenteditable): bring back error style on overflow
  src/components/NcRichContenteditable/NcRichContenteditable.vue
Labels: bug, 3. to review, backport-request, feature: rich-contenteditable

#6732 feat!: split `NcSelect` super component into `NcSelect` and `NcSelectUsers`
  CHANGELOG.md
  src/components/NcSelect/NcSelect.vue
  src/components/NcSelectUsers/NcSelectUsers.vue
  src/components/NcSelectUsers/index.ts
  tests/component/components/NcSelectUsers/NcSelectUsers.spec.ts
  tests/component/components/NcSelectUsers/UserSelect.story.vue
Labels: enhancement, 3. to review, feature: select, 💥 breaking

#6790 chore!: do not export mixins anymore
  CHANGELOG.md
  package.json
  src/index.ts
  vite.config.ts
Labels: 3. to review, 💥 breaking, feature: functions

#6787 chore!: drop tooltip directive
  CHANGELOG.md
  docs/directives/tooltip.md
  src/directives/Tooltip/index.js
  src/directives/Tooltip/index.scss
  src/directives/index.ts
  styleguide.config.cjs
  styleguide/preview.js
Labels: 3. to review, feature: tooltip, 💥 breaking

#6793 chore: prepare release of v8.25.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#6798 chore: release 8.25.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#6799 fix(NcRichText): `references` prop type
  src/components/NcRichText/NcReferenceList.vue
  src/components/NcRichText/NcRichText.vue
Labels: bug, 3. to review, backport-request, feature: richtext

#6261 fix(NcAppContent): don't remove list when showing details in mobile or no-split mode
  src/components/NcAppContent/NcAppContent.vue
Labels: bug, 3. to review

#6807 feat(NcPopover): add new `noFocusTrap` prop
  CHANGELOG.md
  src/components/NcPopover/NcPopover.vue
Labels: 3. to review, feature: popover, 💥 breaking

#6810 ci: use conventional commits in `/*-update` commands
  .github/workflows/command-l10n-update.yml
  .github/workflows/command-playwright-update.yml
Labels: 3. to review

#6823 refactor(NcSavingIndicatorIcon): migrate component to vue
  src/components/NcSavingIndicatorIcon/NcSavingIndicatorIcon.vue
  src/components/NcSavingIndicatorIcon/index.ts
  src/components/index.ts
  tests/component/components/NcSavingIndicator.spec.ts
  tests/component/snapshots/components/NcSavingIndicator.spec.ts-snapshots/Icon-is-rendered-with-correct-color-with-error-false-and-saving-false-prop-1-chromium-linux.png
  tests/component/snapshots/components/NcSavingIndicator.spec.ts-snapshots/Icon-is-rendered-with-correct-color-with-error-false-and-saving-true-prop-1-chromium-linux.png
  tests/component/snapshots/components/NcSavingIndicator.spec.ts-snapshots/Icon-is-rendered-with-correct-color-with-error-true-and-saving-false-prop-1-chromium-linux.png
Labels: 3. to review, refactor ♻️

#6824 chore: adjust vite plugin for vue `<docs>`
  build/docs-plugin.ts
  playwright.config.ts
  vite.config.ts
Labels: 3. to review

#6831 fix(NcAvatar): do not load avatar from server, if iconClass was provided
  src/components/NcAvatar/NcAvatar.vue
  tests/unit/components/NcAvatar/NcAvatar.spec.ts
Labels: bug, 3. to review, feature: avatar, backport-request

#6835 fix(NcMentionBubble): position selectable text aligned with the component
  src/components/NcRichContenteditable/NcMentionBubble.vue
Labels: bug, 3. to review, backport-request, feature: rich-contenteditable

#6821 refactor(NcTimezonePicker): migrate component to Typescript
  l10n/messages.pot
  src/components/NcTimezonePicker/NcTimezonePicker.vue
  src/components/NcTimezonePicker/index.ts
  src/components/NcTimezonePicker/timezone.js
  src/components/NcTimezonePicker/timezoneDataProviderService.ts
  src/components/index.ts
Labels: 3. to review, refactor ♻️

#6811 fix(NcSelectUsers): add missing `search` event
  src/components/NcSelectUsers/NcSelectUsers.vue
  tests/unit/components/NcInputField/NcInputField.spec.ts
  tests/unit/components/NcSelectUsers/search-event.spec.ts
Labels: bug, 3. to review, feature: select, backport-request

#6802 feat(NcPopover): document all properties and remove transparent `floating-vue` wrapper
  CHANGELOG.md
  src/components/NcPopover/NcPopover.vue
  tests/unit/components/NcPopover/logical-placement.spec.ts
Labels: enhancement, 3. to review, feature: popover

#6788 chore: prepare release of v9.0.0-rc.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#6666 feat(NcAppSidebar): add `info` slot
  src/components/NcAppSidebar/NcAppSidebar.vue
  src/components/NcAppSidebarHeader/NcAppSidebarHeader.vue
  src/components/NcAppSidebarHeader/index.ts
  src/components/index.ts
  styleguide.config.cjs
Labels: enhancement, 3. to review, feature: app-sidebar

#6842 chore: prepare release of v8.26.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#6841 chore: update workflows from organization
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/command-l10n-update.yml
  .github/workflows/command-playwright-update.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/npm-publish.yml
  .github/workflows/playwright.yml
  .github/workflows/reuse.yml
Labels: 3. to review

#6845 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6846 [stable8] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
