Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2025-07, with the labels that each got.

#7106 fix(NcRichText): adjust markdown styles after migration
  src/components/NcRichText/NcRichText.vue
Labels: bug, 3. to review, feature: richtext

#7111 refactor(NcSettingsSection): migrate to Typescript and script-setup
  l10n/messages.pot
  src/components/NcSettingsSection/NcSettingsSection.vue
  src/components/NcSettingsSection/index.ts
  src/components/index.ts
  tests/unit/components/NcSettingsSection/NcSettingsSection.spec.ts
Labels: 3. to review, refactor ♻️

#7118 fix(NcNoteCard): too large icon padding
  src/components/NcNoteCard/NcNoteCard.vue
Labels: bug, 3. to review, regression, design, feature: note-card

#7129 refactor!: remove `useFormatDateTime`
  CHANGELOG.md
  src/composables/index.ts
  src/composables/useFormatDateTime/index.ts
  tests/unit/composables/useFormatDateTime.spec.js
Labels: 3. to review, 💥 breaking, refactor ♻️

#7059 refactor!: make all events camelcase and drop deprecated events
  .eslintrc.json
  CHANGELOG.md
  src/components/NcAppContent/NcAppContent.vue
  src/components/NcAppNavigationNewItem/NcAppNavigationNewItem.vue
  src/components/NcAppSidebar/NcAppSidebar.vue
  src/components/NcAppSidebarTab/NcAppSidebarTab.vue
  src/components/NcCollectionList/NcCollectionListItem.vue
  src/components/NcContent/NcContent.vue
  src/components/NcEmojiPicker/NcEmojiPicker.vue
  src/components/NcRelatedResourcesPanel/NcRelatedResourcesPanel.vue
  src/components/NcRichContenteditable/NcRichContenteditable.vue
  src/components/NcRichText/NcReferencePicker/NcProviderList.vue
  src/components/NcRichText/NcReferencePicker/NcReferencePicker.vue
  src/components/NcRichText/NcRichText.vue
  tests/unit/components/NcRichText/NcRichText.spec.js
Labels: 3. to review, 💥 breaking, refactor ♻️

#7136 chore(deps): update `caniuse-lite` to silence warnings
  package-lock.json
Labels: 3. to review, dependencies

#7057 refactor(NcAppContent): clarify props documentation and use capabilities over initial state
  src/components/NcAppContent/NcAppContent.vue
  tests/unit/components/NcAppContent/NcAppContent.spec.ts
Labels: 3. to review, backport-request, refactor ♻️

#7131 fix(l10n): adjust for `@nextcloud/l10n` v3.4.0
  build/l10n-plugin.mts
  package-lock.json
  package.json
  playwright.config.ts
  tests/component/components/NcRichContenteditable.spec.ts
  tests/unit/components/NcDateTime/NcDateTime.spec.js
  tests/unit/utils/l10n.spec.ts
Labels: 3. to review, dependencies, backport-request

#7135 feat(NcPasswordField): allow to set visibility state
  src/components/NcPasswordField/NcPasswordField.vue
  tests/component/components/Nc*Field/NcPassword.story.vue
  tests/component/components/Nc*Field/NcPasswordField.visual.spec.ts
  tests/component/snapshots/components/Nc*Field/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-as-text-can-be-shown-1-chromium-linux.png
  tests/component/snapshots/components/Nc*Field/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-as-text-can-be-shown-by-trailing-button-click-1-chromium-linux.png
  tests/component/snapshots/components/Nc*Field/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-as-text-is-hidden-1-chromium-linux.png
  tests/component/snapshots/components/Nc*Field/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-can-be-shown-1-chromium-linux.png
  tests/component/snapshots/components/Nc*Field/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-can-be-shown-by-trailing-button-click-1-chromium-linux.png
  tests/component/snapshots/components/Nc*Field/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-is-hidden-1-chromium-linux.png
Labels: enhancement, 3. to review, backport-request, feature: input-field

#7051 fix(NcDateTimePicker): correctly import library CSS
  src/components/NcDateTimePicker/NcDateTimePicker.vue
  src/components/NcIconSvgWrapper/NcIconSvgWrapper.vue
  webpack.config.cjs
Labels: bug, 3. to review, feature: datepicker, regression, design

#7151 fix(NcListItem): correctly handle unmounting
  src/components/NcListItem/NcListItem.vue
Labels: bug, 3. to review, feature: list-item

#7157 perf(NcAvatar): ensure avatar does not add mutation observer
  src/components/NcAvatar/NcAvatar.vue
Labels: bug, 3. to review, regression, feature: avatar

#7154 refactor(NcButton): remove redundant style
  src/components/NcButton/NcButton.vue
Labels: bug, 3. to review, regression, backport-request, feature: button

#7156 chore: copy diff from stable8 changelog
  AUTHORS.md
  CHANGELOG.md
Labels: 3. to review, backport-request

#7161 refactor(functions): Make sure only named exports are used (`usernameToColor`)
  CHANGELOG.md
  docs/functions/usernameToColor.md
  src/components/NcAvatar/NcAvatar.vue
  src/functions/index.ts
  src/functions/usernameToColor/index.ts
  src/functions/usernameToColor/usernameToColor.ts
  styleguide/global.requires.js
  tests/unit/functions/usernameToColor/usernameToColor.spec.ts
Labels: 3. to review, backport-request, refactor ♻️

#7165 ci: update workflows from organization
  .github/workflows/command-l10n-update.yml
  .github/workflows/command-playwright-update.yml
  .github/workflows/npm-publish.yml
Labels: 3. to review, Developer experience

#7167 fix(NcInputField): remove browser injected clear button
  src/components/NcInputField/NcInputField.vue
Labels: bug, 3. to review, design, backport-request, feature: input-field

#7162 [stable8] chore: align sorting of package.json
  netlify.toml
  package-lock.json
  package.json
Labels: 3. to review

#7173 refactor(NcRichText): migrate helpers to Typescript
  src/components/NcRichText/NcReferencePicker/utils.js
  src/components/NcRichText/NcReferencePicker/utils.ts
  src/components/NcRichText/NcRichText.vue
  src/components/NcRichText/helpers.ts
  src/components/NcRichText/index.ts
  src/components/NcRichText/placeholder.js
  src/components/NcRichText/remarkPlaceholder.ts
  src/components/NcRichText/remarkUnescape.js
  src/components/NcRichText/remarkUnescape.ts
Labels: 3. to review, feature: richtext, refactor ♻️

#7176 fix(NcModal): use `--border-radius-container`
  src/components/NcModal/NcModal.vue
Labels: bug, 3. to review, design, backport-request

#7185 fix(useIsDarkTheme): provide default value to silence runtime warnings
  src/composables/useIsDarkTheme/constants.ts
  src/composables/useIsDarkTheme/index.ts
Labels: bug, 3. to review, backport-request

#7182 fix(NcAppSidebar): remove slot styling for buttons in the description
  src/components/NcAppSidebar/NcAppSidebar.vue
Labels: bug, 3. to review, feature: app-navigation, backport-request

#7191 chore: prepare release v9.0.0-rc.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#7194 fix(NcAvatar): contacts menu is broken
  src/components/NcAvatar/NcAvatar.vue
Labels: bug, 3. to review, regression, feature: avatar

#7195 fix(NcActionInput): lazy load large children
  src/components/NcActionInput/NcActionInput.vue
Labels: bug, 3. to review, feature: actions

#7201 fix(NcButton): use correct type for `to` prop from VueRouter
  src/components/NcButton/NcButton.vue
Labels: bug, 3. to review, feature: button

#7100 fix(NcButton): render <a> with "to" and prevent wrong context crash
  CHANGELOG.md
  src/components/NcButton/NcButton.vue
  tests/unit/components/NcButton/NcButton.spec.ts
  tests/unit/components/NcButton/button.spec.js
Labels: bug, 3. to review, regression, feature: button

#7202 fix(NcContent): flip skip action image in rtl mode
  src/components/NcContent/NcContent.vue
Labels: bug, 3. to review, accessibility, feature: app-content, backport-request

#7204 [stable8] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#7211 fix: remove asterisk from filename allowing checkout on Windows
  tests/component/components/NcField/FocusSelectTest.story.vue
  tests/component/components/NcField/NcField.spec.ts
  tests/component/components/NcField/NcPassword.story.vue
  tests/component/components/NcField/NcPasswordField.visual.spec.ts
  tests/component/snapshots/components/NcField/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-as-text-can-be-shown-1-chromium-linux.png
  tests/component/snapshots/components/NcField/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-as-text-can-be-shown-by-trailing-button-click-1-chromium-linux.png
  tests/component/snapshots/components/NcField/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-as-text-is-hidden-1-chromium-linux.png
  tests/component/snapshots/components/NcField/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-can-be-shown-1-chromium-linux.png
  tests/component/snapshots/components/NcField/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-can-be-shown-by-trailing-button-click-1-chromium-linux.png
  tests/component/snapshots/components/NcField/NcPasswordField.visual.spec.ts-snapshots/NcPasswordField-password-is-hidden-1-chromium-linux.png
Labels: bug, 3. to review

#7138 refactor(NcProgressbar): migrate component to Typescript and update docs
  src/components/NcProgressBar/NcProgressBar.vue
  src/components/NcProgressBar/index.ts
  src/components/index.ts
Labels: 3. to review, refactor ♻️

#7212 feat(NcColorPicker): add proper open-state handling
  CHANGELOG.md
  src/components/NcColorPicker/NcColorPicker.vue
Labels: enhancement, 3. to review, 💥 breaking

#7160 docs: clarify application containers and especially NcGuestContent
  docs/app-containers.md
  src/components/NcGuestContent/NcGuestContent.vue
  styleguide.config.cjs
Labels: 3. to review, feature: documentation, backport-request

#7200 refactor(NcAppNavigation): migrate component to Typescript and `script-setup`
  src/components/NcAppNavigation/NcAppNavigation.vue
  src/components/NcAppNavigation/NcAppNavigationToggle.vue
  src/components/NcAppNavigation/index.ts
  src/components/NcAppNavigationToggle/index.ts
  src/components/index.ts
  src/globals.d.ts
  tests/unit/components/NcAppNavigation/NcAppNavigation.spec.js
Labels: 3. to review, refactor ♻️

#7232 chore(dev-deps): update nested development dependencies
  package-lock.json
  src/components/NcInputField/NcInputField.vue
  tests/unit/components/NcActions/NcActionButton.spec.ts
Labels: 3. to review, dependencies, refactor ♻️

#7237 fix(NcBreadCrumb): correctly pass container for `NcActions`
  src/components/NcBreadcrumb/NcBreadcrumb.vue
Labels: bug, 3. to review, feature: breadcrumbs
