Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2025-10, with the labels that each got.

#7604 [stable8] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#7620 chore: prepare release of v8.32.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#7621 chore: prepare release of v9.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#7622 [stable8] chore: adjust heading in changelog to match version
  CHANGELOG.md
Labels: 3. to review

#7630 fix(NcInputField): use empty string to fix label position
  src/components/NcInputField/NcInputField.vue
Labels: bug, 3. to review, backport-request, feature: input-field
