Repository nextcloud-libraries/nextcloud-vue, pull requests merged in 2025-01, with the labels that each got.

#6378 [next] fix(NcCounterBubble): small typo in docs
  src/components/NcCounterBubble/NcCounterBubble.vue
Labels: 3. to review, backport-request

#6377 [next] fix(NcAvatar): attributes order
  src/components/NcAvatar/NcAvatar.vue
Labels: bug, 3. to review

#6375 [next] fix(NcActionButton): order in components
  src/components/NcActionButton/NcActionButton.vue
Labels: 3. to review, feature: actions

#6374 [next] chore(deps): update playwrigth deps
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#6373 [next] chore(deps): update vueuse deps
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#6371 [next] chore(deps): update babel deps
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#6376 [next] chore(deps): update vue deps
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#6370 [next] chore(deps): update nextcloud deps
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#6336 fix(NcColorPicker): close popover on submit event
  src/components/NcColorPicker/NcColorPicker.vue
  src/components/NcPopover/NcPopover.vue
Labels: bug, 3. to review, backport-request, feature: colorpicker

#6382 [next] chore(deps): update various dependencies
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#6381 [next] chore(deps): update various development dependencies
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#6385 feat: Allow to import without `dist`
  CHANGELOG.md
  docs/composables.md
  docs/composables/useHotKey.md
  docs/composables/useIsDarkTheme.md
  docs/directives.md
  docs/directives/focus.md
  docs/directives/linkify.md
  docs/directives/tooltip.md
  docs/functions/a11y.md
  docs/functions/emoji.md
  docs/functions/isDarkTheme.md
  docs/functions/spawnDialog.md
  docs/functions/usernameToColor.md
  docs/index.md
  package.json
Labels: enhancement, 3. to review

#6390 [next] fix!: make 'box-sizing: border-box' a default behaviour for all containers
  CHANGELOG.md
  src/assets/NcAppNavigationItem.scss
  src/components/NcAppNavigation/NcAppNavigation.vue
  src/components/NcAppNavigationList/NcAppNavigationList.vue
  src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue
  src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue
  src/components/NcColorPicker/NcColorPicker.vue
  src/components/NcContent/NcContent.vue
  src/components/NcDialog/NcDialog.vue
  src/components/NcModal/NcModal.vue
  src/components/NcPopover/NcPopover.vue
Labels: bug, 3. to review, vue 3

#6389 [next] feat!: Change module import paths - drop `dist` and `.js`-extension
  CHANGELOG.md
  docs/composables.md
  docs/composables/useHotKey.md
  docs/composables/useIsDarkTheme.md
  docs/directives.md
  docs/directives/focus.md
  docs/directives/linkify.md
  docs/directives/tooltip.md
  docs/functions/a11y.md
  docs/functions/emoji.md
  docs/functions/isDarkTheme.md
  docs/functions/spawnDialog.md
  docs/functions/usernameToColor.md
  docs/index.md
  package.json
  vite.config.ts
Labels: 3. to review, vue 3

#6395 fix(NcCounterBubble): show original count in title when shortened
  src/components/NcCounterBubble/NcCounterBubble.vue
  tests/unit/components/NcCounterBubble/NcCounterBubble.spec.js
Labels: bug, 3. to review, backport-request

#6399 feat(Nc*Field): add `#icon` slot for forward compatibility with v9, `#default` slot is deprecated
  src/components/NcInputField/NcInputField.vue
  src/components/NcPasswordField/NcPasswordField.vue
  src/components/NcTextField/NcTextField.vue
Labels: enhancement, 3. to review, feature: input-field

#6359 fix(NcListItem): Fix padding in RTL mode.
  src/components/NcListItem/NcListItem.vue
Labels: bug, feature: list-item, RTL

#6397 chore: Prepare release of v9.0.0-alpha.6
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: 3. to review, vue 3

#6405 [next] chore: restructure `package.json`
  package.json
Labels: 3. to review, refactor ♻️

#6407 fix(bidi): NcAvatar status and interactivity toggle button
  src/components/NcAvatar/NcAvatar.vue
  src/components/NcRichText/NcReferenceWidget.vue
Labels: 3. to review, feature: avatar, backport-request, RTL

#6408 doc: Do not override assets while building the styleguide
  src/components/NcAvatar/NcAvatar.vue
  styleguide.config.js
Labels: feature: documentation

#6387 fix(NcDateTimePickerNative): do not set invalid value
  src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
Labels: bug, 3. to review, feature: datepicker, backport-request

#6419 chore(stylelint): `csstools/use-logical`
  package-lock.json
  package.json
  stylelint.config.js
Labels: 3. to review, RTL

#6418 chore(stylelint): fix scripts to be unix-compatible
  package.json
  src/components/NcRichText/richtext.scss
Labels: 3. to review, backport-request, technical debt

#6380 [next] chore(deps): update vite deps
  package-lock.json
  package.json
  src/assets/variables.scss
  vite.config.ts
Labels: 3. to review, dependencies

#6422 Automated styling update from server
  styleguide/assets/server.css
Labels: 3. to review, dependencies

#6436 ci: block unconventional commits
  .github/workflows/block-unconventional-commits.yml
Labels: 3. to review, backport-request

#6435 ci(deps): Update workflows from organization
  .github/workflows/command-l10n-update.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/l10n.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/npm-publish.yml
  .github/workflows/reuse.yml
  .github/workflows/server-styling-update.yml
  .github/workflows/transifex-approve-merge.yml
Labels: 3. to review, backport-request

#6438 [next] chore: Update translations
  l10n/ar.pot
  l10n/cs.pot
  l10n/da.pot
  l10n/de.pot
  l10n/de_DE.pot
  l10n/en_GB.pot
  l10n/es_AR.pot
  l10n/es_MX.pot
  l10n/fa.pot
  l10n/fi.pot
  l10n/fr.pot
  l10n/ga.pot
  l10n/gl.pot
  l10n/ja.pot
  l10n/ko.pot
  l10n/nb.pot
  l10n/nl.pot
  l10n/pl.pot
  l10n/pt_BR.pot
  l10n/ru.pot
  l10n/sk.pot
  l10n/sr.pot
  l10n/sv.pot
  l10n/tr.pot
  l10n/uk.pot
  l10n/zh_CN.pot
  l10n/zh_HK.pot
Labels: 3. to review, l10n, vue 3

#6430 refactor(useHotKey): migrate code to Typescript
  src/composables/index.js
  src/composables/useHotKey/index.js
  src/composables/useHotKey/index.ts
  src/globals.d.ts
Labels: 3. to review, vue 3, refactor ♻️

#6457 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6458 [next] fix(NcSelect): `required` doesn't work
  src/components/NcSelect/NcSelect.vue
Labels: bug, 3. to review, feature: select

#6264 fix(NcActionRadio): change modelValue to behave like NcCheckboxRadioSwitch
  CHANGELOG.md
  src/components/NcActionRadio/NcActionRadio.vue
Labels: bug, 3. to review, feature: actions, backport-request

#6454 fix(NcDateTimePickerNative): visual fixes
  src/components/NcDateTimePickerNative/NcDateTimePickerNative.vue
Labels: bug, 3. to review, feature: datepicker

#6475 fix(NcActions): Remove on `mousemove` listener for auto focus elements
  src/assets/action.scss
  src/components/NcActions/NcActions.vue
Labels: bug, 3. to review, feature: actions, browser: Safari

#6455 fix(NcAppNavigation + NcUserBubble + NcRichContenteditable): RTL support
  src/assets/NcAppNavigationItem.scss
  src/components/NcAppNavigationCaption/NcAppNavigationCaption.vue
  src/components/NcAppNavigationItem/NcAppNavigationIconCollapsible.vue
  src/components/NcAppNavigationNewItem/NcAppNavigationNewItem.vue
  src/components/NcAppNavigationSettings/NcAppNavigationSettings.vue
  src/components/NcRichContenteditable/NcAutoCompleteResult.vue
  src/components/NcRichContenteditable/NcMentionBubble.vue
  src/components/NcUserBubble/NcUserBubble.vue
Labels: bug, feature: app-navigation, backport-request, feature: userbubble, RTL

#6474 fix(NcRich*): style fixes and RTL support
  src/components/NcRichContenteditable/NcRichContenteditable.vue
  src/components/NcRichText/NcReferencePicker/NcProviderList.vue
  src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue
  src/components/NcRichText/NcReferencePicker/NcSearchResult.vue
  src/components/NcRichText/NcReferenceWidget.vue
  src/components/NcRichText/NcRichText.vue
  src/components/NcRichText/richtext.scss
Labels: bug, 3. to review, feature: rich-contenteditable, feature: richtext, RTL
